(function(g){var window=this;var W4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.B,displayName:g.HH(a),kind:a.A,name:a.C,id:a.Fa,is_servable:a.K,is_default:a.isDefault,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},X4=function(a){return a.g?a.g.languageCode:a.l},zza=function(a,b){var c=new g.GH;
c.l=a.l;c.B=a.B;c.C=a.C;c.A=a.A;c.isDefault=!1;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},Y4=function(a){if(!Aza.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Bza,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Z4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.iQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.l=k},$4=function(a,b,c,d,e){g.iQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},b5=function(a){a=void 0===a?{}:a;
var b="_"+a5++;return new $4(0,0x8000000000000,0,b,a)},c5=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.gb);a.params.gb&&g.Ga(l,a.params.gb);g.Ga(l,c.gb);k.gb=l;g.W.call(this,{G:"div",L:"caption-window",P:{id:"caption-window-"+a.id,dir:1==k.Gk?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},N:[{G:"span",L:"captions-text"}]});this.B=[];this.K=!1;this.F=a;this.D=[];this.H=[];this.Ca=e;this.ya=f;this.C=null;this.Y=.96*e;this.ha=.96*f;this.l=k;this.sa=c;this.A=this.g["captions-text"];this.na=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.M=d/360*16;this.type=0;this.ea=this.M*Cza(l);a=new g.IF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.KO,this);a.subscribe("dragmove",this.JO,this);a.subscribe("dragend",this.IO,this);this.ga=this.fa=0;a="";this.l.Qk&&(a=Y4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.Qk+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":Dza[this.l.textAlign]};this.na&&(b["border-radius"]=a?this.ea/
8+"px":"");g.oh(this.element,b);switch(this.l.Mf){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},Cza=function(a){var b=1+.25*(a.xj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},d5=function(a,b){var c={},d=b.background?b.background:a.l.gb.background;
if(null!=b.hf||b.background){var e=null!=b.hf?b.hf:a.l.gb.hf;d=Y4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.na&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ea/8+"px")}if(null!=b.xj||null!=b.offset)c["font-size"]=a.M*Cza(b)+"px";d=1;e=b.color||a.l.gb.color;if(b.color||null!=b.Lh)e=Y4(e),d=null==b.Lh?a.l.gb.Lh:b.Lh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Zh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.Px&&(k=e=b.Px);var l=a.M/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.uE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.gb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.tf&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Es&&(c.visibility="hidden");return c},Eza=function(a,b,c){a.K=a.K||!!c;
var d={};g.Ga(d,a.l.gb);g.Ga(d,c||b.l);g.Ga(d,a.sa.gb);c=a.D[0];if(c&&d.background==c.background&&d.hf==c.hf&&!!d.Es==!!c.Es&&d.Zh==c.Zh){var e;for(e=0;e<a.D.length;e++)if(g.$b(d,a.D[e])){var f=a.H[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Dd("SPAN");g.oh(f,d5(a,e));a.H[0].appendChild(f);e=1}a.H.length=e;a.D.length=e}else a.H.length=0,a.D.length=0,f=g.Dd("SPAN"),g.oh(f,d5(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Jd(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.B){if(0<e||0!=a.B.length){var m=g.Dd("BR");f.appendChild(m)}f.appendChild(g.Ed("\u00a0"));a.C=g.Ed("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Ed(l):l,m))}a.D.push(d);a.H.push(f);a.B.push(b)},Fza=function(){},f5=function(){this.A=this.l=this.mode=this.o=0;
this.B=new e5(this);this.C=new e5(this);this.g=[];this.clear()},Hza=function(a,b,c){if(255==a&&255==b||!a&&!b)return{An:a,
Bn:b,result:0};a=Gza[a];b=Gza[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{An:a,Bn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{An:a,Bn:b,result:2};return{An:a,Bn:b,result:3}},Jza=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,Iza(a.B,b,c,d))},Kza=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?Jza(a,d.Kx,d.Lx,b):1==d.type&&a.o&496&&Iza(a.C,d.Kx,d.Lx,b)}a.g.length=0},g5=function(){this.g=0},h5=function(){this.l=this.o=this.g=0},i5=function(){this.timestamp=this.we=0},j5=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new i5}this.g=this.l=this.row=0;this.style=new g5;this.B=a;this.A=0},k5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.o[m][p];
if(0!=r.we){0==c&&(c=m,d=p);n=String.fromCharCode(r.we);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.we||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.o[k][m],r=p.we,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=p.timestamp,v<=e&&(e=v),l+=n,p.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},Pza=function(a,b){switch(a){case 0:return Lza[(b&127)-32];
case 1:return Mza[b&15];case 2:return Nza[b&31];case 3:return Oza[b&31]}return 0},l5=function(a){return a.o[a.row][a.l]},m5=function(a,b,c){2<=b&&1<a.l&&(--a.l,l5(a).we=0);
var d=l5(a);d.timestamp=a.B.l+0;d.we=Pza(b,c);32>a.l&&a.l++},Qza=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].Qn(a.o[c+e][f])},n5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},o5=function(a){a.row=0<a.g?a.g:1;
a.l=1;n5(a,0,15)},p5=function(a){this.A=a;
this.B=0;this.style=new g5;this.C=new j5(a);this.D=new j5(a);this.F=new j5(a);this.l=this.C;this.o=this.D;this.g=this.l},q5=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:k5(d,c),o5(a.l),o5(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(k5(d,c),n5(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},Rza=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},Sza=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},e5=function(a){this.l=a;
this.g=new h5;this.B=0;this.o=new p5(a);this.C=new p5(a);this.A=this.o},Iza=function(a,b,c,d){a.g.update();
b=Hza(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.An;c=b.Bn;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&m5(a,0,b),c&96&&m5(a,0,c),0!=b&&0!=c&&3==a.style.g&&k5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;Qza(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));n5(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:m5(b.g,0,32);break a;case 48:57==c?(b=b.g,l5(b).we=0,32>b.l&&b.l++):m5(b.g,1,c&15)}break;case 2:c&32&&m5(b.g,2,c&31);break;case 3:c&32&&m5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Rza(b);break;
case 33:b=b.g;1<b.l&&(--b.l,l5(b).we=0);break;case 36:b=b.g;d=l5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:q5(b,2,d);break;case 38:q5(b,3,d);break;case 39:q5(b,4,d);break;case 40:m5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);o5(d);Sza(b);break;case 43:Sza(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:k5(a,d)}n5(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;k5(a,d);Qza(a,b,b+1,a.g-1);n5(a,a.row,1)}break;case 46:n5(b.o,0,15);break;case 47:k5(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Rza(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},r5=function(){},s5=function(a){this.l=a;
this.g=null},Uza=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Ur("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Tza(d,e,k,b,f,a.firstChild,{},c)},Tza=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.tf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");t5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new Z4(a,b,c,d,n.nodeValue,e||0<m,g.Wb(k)?void 0:k));else{var p={};g.Ga(p,k);Tza(a,b,c,d,e||0<m,n,p,l)}}},u5=function(){this.l={};
this.g=null},v5=function(a){this.A={};
this.H={};this.I={};this.B="_"+a5++;this.C=a;this.F={};this.l=this.g=null;this.D=!0},w5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},x5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},y5=function(a,b){var c=w5(a,b);
if(void 0!=c)return c},z5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return t5.test(c),c},Vza=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.I[d]:a.C);d=y5(b,"mh");null!=d&&(c.Nt=d);d=y5(b,"ju");null!=d&&(c.textAlign=d);d=y5(b,"pd");null!=d&&(c.Gk=d);d=z5(b,"wfc");null!=d&&(c.windowColor=d);d=w5(b,"wfo");void 0!=d&&(c.Qk=d/255);return c},Wza=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.H[d]);d=y5(b,"ap");null!=d&&(c.Mf=d);d=w5(b,"cc");null!=d&&(c.yr=d);d=w5(b,"ah");null!=d&&(c.Qe=d);d=w5(b,"rc");null!=d&&(c.Wp=d);d=w5(b,"av");null!=d&&(c.mg=d);return c},Xza=function(a,b,c,d){var e={};
g.Ga(e,Wza(a,b));g.Ga(e,Vza(a,b));d?g.$b(e,a.C)?(d=a.B,e=a.C):d="_"+a5++:d=b.getAttribute("id")||"_"+a5++;a=w5(b,"t")+c;b=w5(b,"d")||0x8000000000000;return new $4(a,b,0,d,e)},A5=function(a,b,c){this.D=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},B5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},C5=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},D5=function(a,b){this.l=a;
this.track="CC3"==b.B?4:0;this.g=new f5;this.g.o=1<<this.track},Zza=function(a){if(g.u(a))return!1;
a=new A5(a,8,0);return Yza(a)},Yza=function(a){if(!(a.g<a.l.byteLength)||1380139777!=C5(a))return!1;
a.version=B5(a);if(1<a.version)return!1;B5(a);B5(a);B5(a);return!0},$za=function(){this.l=[];
this.g=[]},E5=function(a,b){return b?a.g.concat(a.l):a.g},F5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.La(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.La(c,(0,g.z)(b.I,b))||c.push(b)}},G5=function(){},aAa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.tf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new Z4(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(p),e.l.push(p);else{var r={};g.Ga(r,l);aAa(a,b,c,d,e,!0,p,r,m)}}},H5=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},bAa=function(a,b,c,d){d=Object.assign({Nt:0},d);
return new $4(a,b,c,"_"+a5++,d)},I5=function(a){g.M.call(this);
this.aA=!!a;this.l=new $za;this.D=[];this.g=null},dAa=function(a){var b={};
if(a=X4(a))b.lang=a,cAa.test(a)&&(b.Gk=1);return b},eAa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.u(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.sJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),Zza(b)||(b=g.de(new window.Uint8Array(b))))}if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new G5),a.g.o(b,d);b=g.Ur(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new v5(dAa(c)):a.g=new u5:a.g=new s5(dAa(c)));return a.g.o(b,d)}try{if(Zza(b))return a.g||(a.g=
new D5(e,c)),a.g.o(b,d)}catch(k){g.QD(k)}return[]},J5=function(a){I5.call(this,a.Hn);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},K5=function(){this.qb=[]},L5=function(a,b,c,d,e,f){g.M.call(this);
this.J=a;this.A=b;this.C=new K5;this.g=null;this.H=d;this.K=f;this.o=this.l=null;this.F=c;this.D=e||!1;this.I=new g.Xt(this.vA,1E3,this);g.N(this,this.I);this.B=new g.DF(this);g.N(this,this.B);this.B.O(b,"seekto",this.xB);this.xB(b.getCurrentTime());this.vA()},fAa=function(a,b){var c=a.g;
a.g=g.Ja(a.F.Ag(b).g);c!=a.g&&a.K&&a.K()},gAa=function(a,b){var c=g.MK(b,a.J,{}).Sa(),d={format:"RAW",
withCredentials:!0};a.D&&(d.responseType="arraybuffer");a.o=g.JE(c,d,3,100).then((0,g.z)(a.zT,a));a.l=b;c=a.C;d=a.l.g[0].wa;var e=g.eb(c.qb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.qb[e-1]&&e<c.qb.length&&1==c.qb[e]-d?(g.Ta(c.qb,e),g.Ta(c.qb,e-1)):0<e&&1==d-c.qb[e-1]?c.qb[e-1]=d:e<c.qb.length&&1==c.qb[e]-d?c.qb[e]=d:(g.$a(c.qb,e,0,d),g.$a(c.qb,e+1,0,d)))},M5=function(a,b){I5.call(this);
this.o=a;this.A=b;this.B=null;this.C=!1},hAa=function(a,b){if(b in a.o.g)return a.o.g[b];
if(g.nL(a.o))for(var c in a.o.g){var d=a.o.g[c];if(g.YH(d.info.mimeType)&&("386"!=c||!g.Y(a.A).experiments.g("html5_manifestless_captions_fmt3_killswitch")))return d}return null},N5=function(a,b){return a.Aa&&null!=a.oa||g.Y(b).Ma&&null!=a.oa&&null!=a.oa.g.rawcc},O5=function(a,b,c,d,e,f){c5.call(this,a,b,c,d,e,f);
this.type=1},P5=function(a,b,c,d,e,f){c5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.J=this.T=0;this.X=this.I=window.NaN;this.ra=null;this.da=new g.Xt(this.ET,433,this);g.N(this,this.da)},Q5=function(a){if(!a.T){var b=g.Dd("SPAN");
g.oh(b,d5(a,a.l.gb));a.A.appendChild(b);b.appendChild(g.Ed("M"));var c=b.offsetHeight,d=g.Dd("BR");b.appendChild(d);b.appendChild(g.Ed("M"));a.T=b.offsetHeight-c;a.A.removeChild(b)}return a.T},iAa=function(a){if((0,window.isNaN)(a.I)){var b=a.l.yr;
if(b){var c=g.Dd("SPAN");g.Rd(c,"\u2013".repeat(b));g.oh(c,d5(a,a.l.gb));a.A.appendChild(c);a.I=c.offsetWidth;a.A.removeChild(c)}else a.I=0}return a.I},R5=function(a,b,c,d){I5.call(this,d);
c=c||g.bE(a).hl||"";c=c.split("_").join("-");this.B=g.dE(a,{hl:c});this.A=b;this.C={};this.o=null},U5=function(a){g.tV.call(this,a);
this.A=g.Y(a);this.o=a.getVideoData();this.na=g.WU(a);this.I=a;var b=null,c=g.mD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.WC(c));this.Y=b;this.C={gb:{}};this.F={gb:{}};this.M=[];this.T={};this.Z={};this.K=!1;this.ra="1"==this.o.jc.cc_auto_caps||"1"==this.A.Wb.cc_auto_caps;b="3"==this.A.A&&!!a.app.B&&a.app.B.Jm();this.D=(c=!this.A.experiments.g("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.o.Aa:b;this.ga=c&&b&&this.o.Aa&&N5(this.o,this.I);c=b=this.l=this.B=
this.H=this.J=this.X=this.ha=null;this.D||(b=new g.Ut(this.ZE,void 0,this),g.N(this,b),c=new g.Xt(this.pV,2E3,this),g.N(this,c));this.da=b;this.fa=c;this.W=new g.DF(this);g.N(this,this.W);this.D||this.W.O(a,"resize",this.Kv);this.W.O(a,"onPlaybackAudioChange",this.zQ);this.W.O(a,"crn_captions",this.NM,this);this.W.O(a,"crx_captions",this.OM,this);S5(this,T5(this,"display-settings")||{})},jAa=function(a){if(1==a.A.Zg||1==a.o.Zg||"alwayson"==g.HO(a.o,"yt:cc"))return!0;
if(2==a.A.Zg){var b=T5(a,"module-enabled");if(null!=b)return!!b}if(a.o.captionTracks.length)var c=a.g.getAudioTrack().rr;return"ON"==c||"on"==g.HO(a.o,"yt:cc")},V5=function(a,b){if(a.l&&(void 0===b||!b)||!a.o.captionTracks.length)return!1;
var c=a.g.getAudioTrack();return!!c.jo||"FORCED_ON"==c.rr},X5=function(a,b){if(a.B){var c=E5(a.B.l,b||a.ra);
if(a.H&&a.H.g)return a.H.g;for(var d=[a.o.Yg,a.A.Yg,g.HO(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(X4(c[f])==d[e])return c[f];return a.H&&a.H.Jr?a.H.Jr:(d=c.find(function(a){return a.isDefault}))?d:c[0]||W5(a)}return null},W5=function(a){return a.H&&a.H.jo},kAa=function(a,b){for(var c=a.I.app.B.la().textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},Z5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&Y5(a,"module-enabled",!!b));a.l=b;V5(a)&&(a.l=W5(a));a.load(d)},lAa=function(a){if(a.l!=W5(a)){if(a.K&&!g.KM(a.A)&&!g.RM(a.A)){g.$t(a.fa);
var b=b5({Mf:0,Qe:5,mg:5,Wp:2,textAlign:0,Gk:0,lang:"en"});a.X=[b];var c=["Click "," for settings"];if(!a.ha){var d=new g.kH(g.mpa());g.N(a,d);a.ha=d.element}d=b.end-b.start;var e=g.HH(a.l);e&&a.X.push(new Z4(b.start,d,0,b.id,e));a.X.push(new Z4(b.start,d,0,b.id,c[0]),new Z4(b.start,d,0,b.id,a.ha,!0),new Z4(b.start,d,0,b.id,c[1],!0));g.iV(a.g,a.X);g.Yt(a.fa)}if(a.K||g.KM(a.A))Y5(a,"module-enabled",!0),a.H&&(a.H.g=a.l);(a=g.UU(a.g.app))&&a.C&&g.$O(a.C.o)}},mAa=function(a,b){var c=g.X_(a.na,!0).height;
if(!c)return null;var d=a.na.Na();switch(null!=b.params.Nt?b.params.Nt:b.params.aW?2:1<b.l.length?1:0){case 1:return new O5(b,a.C,a.F,c,d.width,d.height);case 2:return new P5(b,a.C,a.F,c,d.width,d.height);default:return new c5(b,a.C,a.F,c,d.width,d.height)}},S5=function(a,b,c){var d=$5.gb;
a.C={};g.Ga(a.C,$5);a.C.gb={};g.Ga(a.C.gb,d);a.F={gb:{}};var e=b.backgroundOverride?a.F:a.C,f=b.background||d.background;t5.test(f);e.gb.background=f;e=b.colorOverride?a.F:a.C;f=b.color||d.color;t5.test(f);e.gb.color=f;e=b.windowColorOverride?a.F:a.C;f=b.windowColor||$5.windowColor;t5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.C;f=b.backgroundOpacity;null==f&&(f=d.hf);e.gb.hf=f;e=b.fontSizeIncrementOverride?a.F:a.C;f=b.fontSizeIncrement;null==f&&(f=d.xj);e.gb.xj=f;f=b.fontStyleOverride?
a.F:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.tf?3:d.bold?1:d.tf?2:0);f=f.gb;switch(e){case 1:f.bold=!0;delete f.tf;break;case 2:delete f.bold;f.tf=!0;break;case 3:f.bold=!0;f.tf=!0;break;default:delete f.bold,delete f.tf}e=b.textOpacityOverride?a.F:a.C;f=b.textOpacity;null==f&&(f=d.Lh);e.gb.Lh=f;e=b.windowOpacityOverride?a.F:a.C;f=b.windowOpacity;null==f&&(f=$5.Qk);e.Qk=f;e=b.charEdgeStyleOverride?a.F:a.C;f=b.charEdgeStyle;null==f&&(f=d.Zh);e.gb.Zh=f;e=b.fontFamilyOverride?a.F:a.C;f=b.fontFamily;null==
f&&(f=d.fontFamily);e.gb.fontFamily=f;a.loaded&&a.Kv();c&&Y5(a,"display-settings",b)},oAa=function(a,b){if(b&&!a.J){var c=b5({Gk:0,
lang:"en"});a.J=[c,new Z4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.iV(a.g,a.J)}else!b&&a.J&&(nAa(a,a.J),a.J=null)},nAa=function(a,b){g.kV(a.g,b);
(0,g.B)(b,function(a){g.Ua(this.M,a)},a);
a.da.zl()},pAa=function(a,b){return a&&g.u(a)&&t5.test(a)?a:b},qAa=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},rAa=function(a,b){return g.va(a)&&!(0,window.isNaN)(a)?g.cd(a,-2,4):b},T5=function(a,b){if(!a.Y)return null;
try{var c=a.Y.get(b)}catch(d){a.Y.remove(b)}return c},Y5=function(a,b,c){if(a.Y)try{a.Y.set(b,c)}catch(d){}};
g.mY.prototype.qj=g.ca(9,function(){for(var a=g.pd(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.Jd(a[b])});
g.M_.prototype.qj=g.ca(8,function(){this.g.qj()});
g.mY.prototype.Jm=g.ca(7,function(){return!!this.g.textTracks});
g.M_.prototype.Jm=g.ca(6,function(){return this.g.Jm()});
g.mY.prototype.Tk=g.ca(5,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.M_.prototype.Tk=g.ca(4,function(a){this.g.Tk(a)});
g.$I.prototype.uo=g.ca(2,function(a){return(a=this.hi(a))?a.l:0});
g.dL.prototype.uo=g.ca(1,function(){return 0});
g.GH.prototype.I=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var cAa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Bza=/#(.)(.)(.)/,Aza=/^#(?:[0-9a-f]{3}){1,2}$/i,t5=/^#(?:[0-9a-f]{3}){1,2}$/i;var Dza=["left","right","center"];var $5={windowColor:"#080808",Qk:0,textAlign:2,Mf:7,Qe:50,mg:100,gb:{background:"#080808",hf:.75,Zh:0,color:"#fff",fontFamily:4,xj:0,Lh:1,offset:1}};g.q(Z4,g.iQ);g.q($4,g.iQ);var a5=0;g.q(c5,g.W);g.h=c5.prototype;g.h.KO=function(a,b){var c=g.Fh(this.element,this.element.parentElement);this.fa=a-c.x;this.ga=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.JO=function(a,b){var c=g.Ih(this.element),d=a-this.fa-.02*this.Ca,e=b-this.ga-.02*this.ya,f=(d+c.width/2)/this.Y*3;f=Math.floor(g.cd(f,0,2));var k=(e+c.height/2)/this.ha*3;k=Math.floor(g.cd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Y;d=100*g.cd(d,0,1);c=(e+k/2*c.height)/this.ha;c=100*g.cd(c,0,1);this.F.params.Mf=l;this.F.params.mg=c;this.F.params.Qe=d;this.l.Mf=l;this.l.mg=c;this.l.Qe=d;this.PD()};
g.h.IO=function(){g.kq(this.element,"ytp-dragging")};
g.h.PD=function(){this.Wi(this.B)};
g.h.Tb=function(){return this.type};
g.h.Wi=function(a){var b=Math.min(this.Yy(),this.Y),c=this.Xy();g.oh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gr(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.Qe+2,e=this.l.Mf;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.mg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.oh(this.element,a)};
g.h.gr=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.K||this.B.length>b)b=0,this.K=!1,this.B=[],this.D=[],this.H=[],this.C=null,g.Hd(this.A);for(;b<a.length;b++)Eza(this,a[b])};
g.h.Yy=function(){return 0};
g.h.Xy=function(){return 0};Fza.prototype.B=function(){};f5.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
f5.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Gza=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];g5.prototype.set=function(a){this.g=a};
g5.prototype.get=function(){return this.g};
h5.prototype.clear=function(){this.g=0};
h5.prototype.update=function(){this.g=2==this.g?1:0};
h5.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
i5.prototype.Qn=function(a){this.we=a.we;this.timestamp=a.timestamp};
i5.prototype.reset=function(){this.timestamp=this.we=0};
j5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.we?a+"_":a+String.fromCharCode(d.we)}a+="\n"}return a};
j5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var Lza=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Mza=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Nza=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Oza=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];p5.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
e5.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};r5.prototype.reset=function(){};g.q(s5,r5);s5.prototype.o=function(a){var b=[];this.g||(this.g=b5(this.l),b.push(this.g));a=Array.from(a.firstChild.childNodes);a=g.ma(a);for(var c=a.next();!c.done;c=a.next())Uza(c.value,this.g.id,b);return b};g.q(u5,r5);
u5.prototype.o=function(a){var b=[];this.g||(this.g=b5(),this.l[this.g.id]=this.g,b.push(this.g));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.l[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=b5());
var k={};f&&(g.Ga(k,f.params),f=f.params.gb)&&(k.gb={},g.Ga(k.gb,f));e.getAttribute("rc")&&(k.Wp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.yr=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Mf=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Qe=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.mg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Gk=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Gk=0));e.getAttribute("bc")&&(k.gb||(k.gb={}),k.gb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.gb||(k.gb={}),k.gb.hf=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.gb||(k.gb={}),k.gb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.aW=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+a5++;c=new $4(c,f,0,e,k)}else c=null}this.l[d]=c;b.push(c);break;case "text":for(d=[],Uza(a,this.g.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.l[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.q(v5,r5);v5.prototype.reset=function(){this.F={};this.l=this.g=null;this.D=!0};
v5.prototype.o=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.ma(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.ma(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Ga(l,this.A[m]);m=x5(c,"b");null!=
m&&(l.bold=m);m=x5(c,"i");null!=m&&(l.tf=m);m=x5(c,"u");null!=m&&(l.underline=m);m=y5(c,"et");null!=m&&(l.Zh=m);m=y5(c,"of");null!=m&&(l.offset=m);m=z5(c,"bc");null!=m&&(l.background=m);m=z5(c,"ec");null!=m&&(l.Px=m);m=z5(c,"fc");null!=m&&(l.color=m);m=y5(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=w5(c,"sz");void 0!=m&&(l.xj=m/100-1);m=w5(c,"bo");void 0!=m&&(l.hf=m/255);c=w5(c,"fo");void 0!=c&&(l.Lh=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.I[d]=Vza(this,c);break;case "wp":d=c.getAttribute("id"),
this.H[d]=Wza(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.ma(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=Xza(this,d,e,!1);(d=this.F[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.F[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!x5(d,"a");n=(w5(d,"t")||0)+n;var p=w5(d,"d")||5E3;m||(!this.D&&this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=
""));var r=m?6:5,v=this.A[d.getAttribute("p")],D=d.childNodes;D.length&&(this.D=null!=d.getAttribute("d"));for(var H=0;H<D.length;H++){var L=D[H];0<H&&(m=!0);var T=void 0;1==L.nodeType&&(T=L);if(T&&"s"==T.tagName){var ha=T;L=n;T=p;var db=l,sa=m,Ud=r,Bh=ha.textContent?ha.textContent:"",rb=this.A[ha.getAttribute("p")];ha=w5(ha,"t")||0;L=new Z4(L+ha,T-ha,Ud,db,Bh,sa,rb)}else L=new Z4(n,p,r,l,L.textContent||"",m,v);k.push(L);this.l=L}if(0<k.length)for(k[0].windowId==this.B&&(this.g=Xza(this,d,e,!0),c.push(this.g)),
d=g.ma(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,this.g.l.push(k),c.push(k)}e=c}else e=[];return e};g.q(A5,Fza);A5.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+a5++;c=c/1E3-this.D;d=d/1E3-this.D;a=new $4(c,d-c,5,f,{textAlign:0,Mf:0,Qe:2.5*b,mg:5.33*a});e=new Z4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.q(D5,r5);D5.prototype.o=function(a){a=new A5(a,a.byteLength,this.l);if(Yza(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=C5(a)*(1E3/45):1==a.version&&(a.A=4294967296*C5(a)+C5(a)),a.C=B5(a);0<a.C;a.C--){var b=B5(a),c=B5(a),d=B5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,Kx:c,Lx:d,order:b.g.length}))}Kza(this.g,a);return a.o}return[]};
D5.prototype.reset=function(){this.g.clear()};g.q(G5,r5);
G5.prototype.o=function(a,b){for(var c=[],d=a.split(sAa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!tAa.test(f)){var l=a6.exec(f);if(l&&4<=l.length){var m=H5(l[1]),n=H5(l[2])-m;m+=k;var p,r=p=void 0,v=void 0,D=void 0,H=l[3];l={textAlign:2};H=g.ma(H?H.split(" "):[]);for(var L=H.next();!L.done;L=H.next())if(L=L.value.split(":"),2==L.length){var T=L[1];switch(L[0]){case "line":L=T.split(",");L[0].endsWith("%")&&(D=L[0],l.mg=Number.parseInt(D,10),2==L.length&&(v=L[1].trim()));break;case "position":L=T.split(",");
r=L[0];l.Qe=Number.parseInt(r,10);2==L.length&&(p=L[1].trim());break;case "align":switch(T){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}D||(l.mg=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.Qe=0;break;case 1:l.Qe=100;break;default:l.Qe=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Mf=0>r||8<r?7:r;p=l;f=f.substring(a6.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=bAa(m,n,5,r),n=new Z4(m,n,5,k.id,p,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),k.l.push(n);else for(v=p.split(uAa),1==v.length?(p=5,r=bAa(m,n,p,r)):(D=p=6,r=Object.assign({yr:32},r),r=new $4(m,n,D,"_"+a5++,r)),c.push(r),D=m,l=0;l<v.length;l++)H=v[l],0==l%2?(L=g.Ur("<html>"+H+"</html>"),L.getElementsByTagName("parsererror").length?
(T=L.createElement("span"),T.appendChild(L.createTextNode(H))):T=L.firstChild,aAa(this,D,n-(D-m),p,r,0<l,T,f,c)):D=H5(H)+k}a6.lastIndex=0}}return c};
var tAa=/^NOTE/,sAa=/(?:\r\n|\r|\n){2,}/,a6=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),uAa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.q(I5,g.M);I5.prototype.trackCount=function(){return E5(this.l,!0).length};
I5.prototype.Od=function(){this.g=null};
I5.prototype.V=function(){g.M.prototype.V.call(this);this.Od()};
I5.prototype.wD=function(){return!1};g.q(J5,I5);g.h=J5.prototype;g.h.Gt=function(a,b){var c=this.wl(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Od();this.o=g.lE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Ht=function(a,b,c,d){this.A=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())F5(this.l,c.value);a()};
g.h.wl=function(a){var b=a.Sa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.dE(b,c)};
g.h.Od=function(){I5.prototype.Od.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Od();I5.prototype.V.call(this)};K5.prototype.contains=function(a){a=g.eb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
K5.prototype.length=function(){return this.qb.length/2};g.q(L5,g.M);g.h=L5.prototype;g.h.V=function(){g.M.prototype.V.call(this);this.o&&this.o.cancel()};
g.h.xB=function(a){var b=this;if(this.F.Vj())var c=this.B.O(this.A,"progresssync",function(){b.F.index.Ib()&&(b.reset(),b.g=null,fAa(b,b.A.getCurrentTime()),b.B.Ea(c))});
else fAa(this,a)};
g.h.reset=function(){this.C=new K5;this.o&&(this.o.cancel(),this.o=null)};
g.h.vA=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Hg(a);!a||this.o||this.g&&30<this.g.startTime-this.A.getCurrentTime()||(a=this.g,a=a.g.bk(a),!g.Y(this.A).experiments.g("disable_captions_unknown_requests")&&!a.g[0].duration)||(this.C.contains(a.g[0].wa)||gAa(this,a),this.g=g.Ja(a.g));this.I.start()};
g.h.zT=function(a){var b=!(this.D?a.response:a.responseText)||400<=a.status;if(!g.Y(this.A).experiments.g("disable_captions_redirects_redux")){var c=g.iL(a);if(c){a=g.MK(this.l,this.J,{});b=this.l;g.IK(b.l,a,c);b.requestId=a.get("req_id");gAa(this,this.l);return}}b||null===this.H||(this.D?this.H(a.response,1E3*this.l.g[0].startTime,this.l.g[0].wa):this.H(a.responseText,1E3*this.l.g[0].startTime,this.l.g[0].wa));this.o=this.l=null};g.q(M5,I5);g.h=M5.prototype;g.h.Gt=function(a,b){this.Od();var c=hAa(this,a.l);if(c){var d=c.index.uo(c.index.kf());g.Y(this.A).experiments.g("html5_disable_caption_starttime")||(d-=c.index.Ld(c.index.kf()));d*=1E3;var e=g.Y(this.A).Ma;this.B=new L5(new g.rK,this.A,c,function(c,e,l){b(c,a,e,d,l)},e||g.UH(c.info),(0,g.z)(function(){this.B&&this.B.reset();
this.g&&this.g.reset();this.C=!0},this))}};
g.h.wD=function(){var a=this.C;this.C=!1;return a};
g.h.Ht=function(a){if(g.Y(this.A).Ma)F5(this.l,new g.GH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),F5(this.l,new g.GH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.o.g){var c=this.o.g[b];if(g.YH(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.Y(this.A).experiments.g("html5_manifestless_captions_fmt3_killswitch"))){var d="en",e="English",f=".en";if(c=
c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;F5(this.l,new g.GH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Od=function(){I5.prototype.Od.call(this);this.B&&(this.B.dispose(),this.B=null)};
g.h.wl=function(){return""};
g.h.V=function(){this.Od();I5.prototype.V.call(this)};g.q(O5,c5);O5.prototype.gr=function(a){var b=this.F.l;c5.prototype.gr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Ga(d,c.l);g.Ga(d,vAa);var e=c.l;var f=d}Eza(this,c,d)}};
var vAa={Es:!0};g.q(P5,c5);g.h=P5.prototype;g.h.PD=function(){g.Zt(this.da)};
g.h.ET=function(){g.kq(this.element,"ytp-rollup-mode");this.Wi(this.ra,!0)};
g.h.Yy=function(){return this.J};
g.h.Xy=function(){return this.F.params.Wp*Q5(this)};
g.h.Wi=function(a,b){this.ra=a;if(Q5(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.J;this.J=0;c5.prototype.Wi.call(this,a);d=this.A.offsetWidth+1;this.J=Math.max(iAa(this),c,d);c=this.F.params.Wp*Q5(this)-this.A.offsetHeight;c!=this.X&&(b||(0,window.isNaN)(this.X)||(g.S(this.element,"ytp-rollup-mode"),g.Yt(this.da)),g.oh(this.A,"transform",c?"translateY("+c+"px)":""),this.X=c);c5.prototype.Wi.call(this,a)}else c5.prototype.Wi.call(this,
a)};g.q(R5,I5);g.h=R5.prototype;g.h.Gt=function(a,b){var c=this.wl(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Od();this.o=g.lE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Ht=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.aA&&(b.asrs=1);d=g.dE(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),p=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),D=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
L="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");F5(d,new g.GH({formats:l,format:c,languageCode:n,languageName:p,name:r,kind:v,id:D,is_servable:!0,is_translateable:L,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:r,
is_default:v},this.C[l.languageCode]=l.languageName,this.D.push(new g.FH(l))}a()},this);
this.Od();this.o=g.lE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.wl=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.C,kind:a.A,fmt:a.o};a.g&&(c.tlang=X4(a));return b=g.dE(b,c)};
g.h.Od=function(){I5.prototype.Od.call(this);this.o&&this.o.abort()};
g.h.V=function(){this.Od();I5.prototype.V.call(this)};g.q(U5,g.tV);g.h=U5.prototype;g.h.V=function(){if(this.D){var a=this.I.app.B;a&&a.qj()}else oAa(this,!1);g.tV.prototype.V.call(this)};
g.h.VA=function(){return this.D?!this.o.Aa:this.ga||V5(this)?!0:jAa(this)};
g.h.load=function(a){g.tV.prototype.load.call(this);this.H=this.g.getAudioTrack();if(this.B||a)this.l&&(this.D&&!this.A.experiments.g("disable_native_caption_api")?kAa(this,!0):a?this.fD(a,this.l):3!=this.g.Pa()&&this.B.Gt(this.l,(0,g.z)(this.fD,this))),this.l&&this.l!=W5(this)?this.g.va("captionschanged",W4(this.l)):this.g.va("onCaptionsTrackListChanged");else{var b;N5(this.o,this.I)?b=new M5(this.o.oa,this.g):this.o.captionTracks.length?b=new J5(this.o):b=new R5(this.o.In,this.o.videoId,this.o.Yg||
this.A.Yg||g.HO(this.o,"yt:cc_default_lang")||this.A.ya,this.o.Hn);this.B=b;b.Ht((0,g.z)(this.lU,this),!0,this.D?"vtt":void 0,this.g.getAudioTrack())}};
g.h.unload=function(){this.D?this.A.experiments.g("disable_native_caption_api")?this.I.app.B.qj():this.l&&kAa(this,!1):(this.fa&&g.$t(this.fa),g.lV(this.g,"captions"),this.M=[],this.B&&this.B.Od(),this.J&&g.iV(this.g,this.J),this.Kv());g.tV.prototype.unload.call(this);var a=g.UU(this.g.app);a&&a.C&&g.$O(a.C.o);this.g.va("captionschanged",{})};
g.h.lU=function(){var a;this.K||jAa(this)?a=X5(this,this.K):V5(this)&&(a=W5(this));if(this.D||this.ga){for(var b=E5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.HH(e),srclang:X4(e),id:e.toString()};this.ga||(f.src=this.B.wl(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}this.I.app.B.Tk(c);(a=this.I.app.B.la())&&a.textTracks&&a.textTracks.addEventListener&&!this.A.experiments.g("disable_native_caption_api")&&this.W.O(a.textTracks,"change",this.mU)}else!this.l&&a&&
Z5(this,a),this.g.va("onCaptionsTrackListChanged"),this.g.va("onApiChange")};
g.h.mU=function(){for(var a=this.I.app.B.la().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=E5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&Z5(this,b,!0)};
g.h.nW=function(){this.A.experiments.g("disable_native_caption_api")?this.loaded&&!this.D&&this.unload():!this.l&&this.D||this.unload()};
g.h.fD=function(a,b,c,d,e){a&&(this.B.wD()&&(this.M=[],g.lV(this.I,"captions"),this.da.zl()),a=eAa(this.B,a,b,c,d),this.A.experiments.g("debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new $4(c,b,0,"_"+a5++,{Mf:2,
Qe:100,mg:0}),a.push(d),e=new Z4(c,b,0,d.id,"sq="+e),a.push(e)),g.iV(this.g,a),this.K&&!this.ga&&lAa(this),this.K=!1)};
g.h.NM=function(a){this.M.push(a);this.da.zl()};
g.h.OM=function(a){g.Ua(this.M,a);var b=N5(this.o,this.I)&&this.A.Ma;!this.A.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.kV(this.g,[a]);this.da.zl()};
g.h.fV=function(a){if(a instanceof $4){var b=this.T[a.id];b&&b.F!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=mAa(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.Z[b]||(this.Z[b]=[]),this.Z[b].push(a)};
g.h.pV=function(){nAa(this,this.X);this.X=null};
g.h.ZE=function(){this.da.stop();g.Xb(this.Z);this.M.sort(g.kQ);var a=this.M;if(this.J){var b=(0,g.Kd)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.B)(a,this.fV,this);g.Jb(this.T,function(a,b){this.Z[b]?(a.element.parentNode||g.nV(this.g,a.element,4),a.Wi(this.Z[b])):(a.dispose(),delete this.T[b])},this)};
g.h.OD=function(){S5(this,{},!0)};
g.h.gs=function(){var a=$5.gb;a={background:a.background,backgroundOpacity:a.hf,charEdgeStyle:a.Zh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.xj,fontStyle:a.bold&&a.tf?3:a.bold?1:a.tf?2:0,textOpacity:a.Lh,windowColor:$5.windowColor,windowOpacity:$5.Qk};var b=T5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Nv=function(a,b){var c={};g.Ga(c,T5(this,"display-settings"));g.Ga(c,a);S5(this,c,b);this.g.R("captionssettingschanged")};
g.h.Kv=function(){!this.D&&this.loaded&&(g.Jb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.ZE())};
g.h.Vt=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.cd(b,-2,4);this.Nv({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&Z5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.A.yb&&Y5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.D)break;if(!g.Ca(b))break;if(g.Wb(b)){Z5(this,null,!0);break}var d;c=E5(this.B.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.B!=b.languageName||(d=b.translationLanguage?
zza(f,b.translationLanguage):f)}!d||d==this.l&&this.loaded||Z5(this,d,!0)}else return this.loaded&&this.l&&this.l!=W5(this)?W4(this.l):{};return"";case "tracklist":return this.B?(0,g.G)(E5(this.B.l,!(!b||!b.includeAsr)),function(a){return W4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":d=this.gs();if(g.KM(this.A)&&b&&g.Ca(b))if(b.reset)this.OD();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=pAa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=qAa(b[c],d[c]);break;case "charEdgeStyle":var k=g.Q1[b[c]];f[c]=g.va(k)?k:d[c];break;case "fontSizeIncrement":f[c]=rAa(b[c],d[c]);break;case "fontFamilyOption":k=g.P1[b[c]];f.fontFamily=
g.va(k)?k:d[c];break;case "fontStyle":k=g.R1[b[c]],f[c]=g.va(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Nv(f,!0);d=this.gs()}d.fontFamilyOption=g.jva[d.fontFamily];d.charEdgeStyle=g.kva[d.charEdgeStyle];d.fontStyle=g.lva[d.fontStyle];return d;case "sampleSubtitles":this.D||void 0==b||oAa(this,!!b);break;case "xmlTrack":b&&this.A.yb&&(this.D||Z5(this,new g.GH({languageName:b.name}),!1,b.xml))}};
g.h.LM=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.A.yb&&a.push("stickyLoading","xmlTrack");return a};
g.h.MM=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.PE=function(){this.loaded&&this.l&&this.l!=W5(this)?(Y5(this,"module-enabled",!1),this.unload(),V5(this,!0)&&Z5(this,W5(this),!1)):Z5(this,this.l==W5(this)?X5(this,!0):this.l,!0)};
g.h.zQ=function(){var a=this.l==W5(this);V5(this,a)?Z5(this,this.g.getAudioTrack().jo,!1):this.o.captionTracks.length&&(this.loaded&&this.unload(),this.VA()&&(a?Z5(this,X5(this),!1):this.load()))};g.jY.captions=U5;})(_yt_player);
