(function(g){var window=this;var wAa=function(a,b,c,d){var e=b.Yb();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.cd(c,d?d:"mqdefault.jpg");var k=b instanceof g.oO?g.LV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.lQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.oO?b.Aa:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.Uk||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.yl(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.nQ&&(c.playlist_length=b.getLength());a.update(c)},b6=function(a,b){g.qH.call(this,{G:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.l=a;this.created=!1},c6=function(a){g.W.call(this,{G:"div",
L:"ytp-upnext",P:{"aria-label":"{{aria_label}}"},N:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",N:[{G:"span",L:"ytp-upnext-header",aa:"Up Next"},{G:"span",L:"ytp-upnext-title",aa:"{{title}}"},{G:"span",L:"ytp-upnext-author",aa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},N:[{G:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},N:[{G:"circle",L:"ytp-svg-autoplay-circle",
P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",N:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",aa:"Autoplay is paused"}]}]});this.B=null;
var b=this.g["ytp-upnext-cancel"];this.B=new g.W({G:"button",ca:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},aa:"Cancel"});g.N(this,this.B);this.B.U("click",this.HQ,this);this.B.ua(b);this.l=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.H=new g.Xt(this.Mn,5E3,this);g.N(this,this.H);this.I=0;this.O(this.g["ytp-upnext-autoplay-icon"],"click",this.US);this.uC();this.O(a,"autonavvisibility",this.uC);this.O(a,"mdxnowautoplaying",
this.gS);this.O(a,"mdxautoplaycanceled",this.hS);this.O(a,"mdxautoplayupnext",this.cF);3==this.l.Pa()&&(a=(a=g.TU(g.OU(this.l)))?a.GJ():null)&&this.cF(a)},xAa=function(a,b){a.C=b;
wAa(a,b,g.Y(a.l),"hqdefault.jpg")},d6=function(a,b){if(!a.A){g.VF("a11y-announce","Up Next "+a.C.title);
a.I=g.fG();a.A=new g.Xt((0,g.z)(a.dr,a,b),25);a.dr(b);var c=b||g.Y(a.l).experiments.l("autoplay_time")||1E4;a.l.va("onAutonavCoundownStarted",c)}g.kq(a.element,"ytp-upnext-autoplay-paused")},f6=function(a){e6(a);
a.I=g.fG();a.dr();g.S(a.element,"ytp-upnext-autoplay-paused")},e6=function(a){a.A&&(a.A.dispose(),a.A=null)},g6=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.l);if(c.experiments.g("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.C.Yb(),a.Mn(),a.D=new window.Notification("Up Next",{body:d.title,icon:d.cd(c)}),a.F=a.O(a.D,"click",a.JS),a.H.start())}e6(a);a.l.jk(!1,b)},yAa=function(a){b6.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new g.W({G:"div",L:"ytp-subscribe-card",N:[{G:"img",L:"ytp-author-image",P:{src:b.profilePicture}},{G:"div",L:"ytp-subscribe-card-right",N:[{G:"div",L:"ytp-author-name",aa:b.author},{G:"div",L:"html5-subscribe-button-container"}]}]});g.N(this,this.A);this.A.ua(this.element);this.B=new g.z_("Subscribe",null,"Unsubscribe",null,!0,!1,b.If,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.B);this.B.ua(this.A.g["html5-subscribe-button-container"]);this.hide()},h6=
function(a){var b=g.Y(a),c=g.yI||g.df?{style:"will-change: opacity"}:void 0,d=b.g,e=["ytp-videowall-still"];
b.l&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",ca:e,P:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{G:"div",L:"ytp-videowall-still-image",P:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",N:[{G:"span",L:"ytp-videowall-still-info-bg",N:[{G:"span",L:"ytp-videowall-still-info-content",P:c,N:[{G:"span",L:"ytp-videowall-still-info-title",aa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",aa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",aa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",aa:"{{duration}}"}]}]}]},{G:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",N:[" (",{G:"span",aa:"{{playlist_length}}"},")"]}]},{G:"span",ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
N:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",aa:" (50+)"}]}]});this.C=d;this.l=a;this.A=null;this.B=new g.DF(this);g.N(this,this.B);this.U("click",this.F);this.U("keypress",this.H);this.B.O(a,"videodatachange",this.D);g.Y(a).X&&(a=a.app.fa,b=this.element,g.Pa(a.g,b),g.Sa(a.g,b),c=String(a.F++),b.setAttribute("data-visual-id",c),g.Ze(this,(0,g.z)(a.D,a,b)));this.D()},i6=function(a){b6.call(this,a,"videowall-endscreen");
this.K=a;this.F=0;this.B=[];this.H=this.D=this.C=null;this.I=this.T=!1;this.W=new g.DF(this);g.N(this,this.W);this.J=new g.Xt(g.Fa(g.S,this.element,"ytp-show-tiles"),0);g.N(this,this.J);var b=new g.W({G:"button",ca:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},N:[g.GV()]});g.N(this,b);b.ua(this.element);b.U("click",this.CO,this);this.M=new g.kH({G:"div",L:"ytp-endscreen-content"});g.N(this,this.M);this.M.ua(this.element);b=new g.W({G:"button",ca:["ytp-button","ytp-endscreen-next"],
P:{"aria-label":"Next"},N:[g.HV()]});g.N(this,b);b.ua(this.element);b.U("click",this.BO,this);this.A=new c6(a);g.N(this,this.A);g.nV(this.l,this.A.element,4);this.hide()},j6=function(a){return g.oV(a.l)&&a.Bx()&&!a.H},zAa=function(a,b){return(0,g.G)(b.suggestions,function(b){b=g.pY(b);
g.N(a,b);return b})},k6=function(a){var b=a.qu();
b!=a.T&&(a.T=b,a.l.R("autonavvisibility"))},l6=function(a){g.tV.call(this,a);
this.l=null;this.o=new g.DF(this);g.N(this,this.o);this.A=g.Y(a);AAa(a)?this.l=new i6(this.g):this.A.Ga?this.l=new yAa(this.g):this.l=new b6(this.g);g.N(this,this.l);g.nV(this.g,this.l.element,4);this.ND();this.o.O(a,"videodatachange",this.ND,this);this.o.O(a,"crn_endscreen",this.DM,this);this.o.O(a,"crx_endscreen",this.EM,this)},AAa=function(a){a=g.Y(a);
return a.zd&&!a.Ga};
g.q(b6,g.qH);b6.prototype.create=function(){this.created=!0};
b6.prototype.destroy=function(){this.created=!1};
b6.prototype.Bx=function(){return!1};
b6.prototype.qu=function(){return!1};g.q(c6,g.W);g.h=c6.prototype;g.h.Mn=function(){this.D&&(this.H.stop(),this.Ea(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.uC=function(){g.pH(this,g.PU(this.l))};
g.h.JS=function(){window.focus();this.Mn()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.dr=function(a){a=a||g.Y(this.l).experiments.l("autoplay_time")||1E4;var b=Math.min(g.fG()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Pa()?g6(this,!0):this.A&&this.A.start()};
g.h.US=function(a){!g.Pd(this.B.element,g.rF(a))&&g.qX(a,this.l)&&g6(this)};
g.h.HQ=function(){g.RU(this.l,!0)};
g.h.gS=function(a){this.l.Pa();this.show();d6(this,a)};
g.h.cF=function(a){this.l.Pa();this.C&&this.C.Yb().videoId==a.Yb().videoId||xAa(this,a)};
g.h.hS=function(){this.l.Pa();e6(this);this.hide()};
g.h.V=function(){e6(this);this.Mn();g.W.prototype.V.call(this)};g.q(yAa,b6);g.q(h6,g.W);h6.prototype.Ak=function(){g.rV(this.l,this.element);var a=this.A.Yb().videoId,b=this.A.getPlaylistId();g.H0(this.l.app,a,this.A.Md,b,void 0,void 0,void 0)};
h6.prototype.F=function(a){g.qX(a,this.l,this.C,this.A.Md||void 0)&&this.Ak()};
h6.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.wF(a)||(this.Ak(),g.vF(a))}};
h6.prototype.D=function(){var a=this.l.getVideoData(),b=g.Y(this.l);this.C=a.isDni?!1:b.g};g.q(i6,b6);g.h=i6.prototype;g.h.create=function(){b6.prototype.create.call(this);var a=this.l.getVideoData();a&&(this.C=zAa(this,a),this.D=a);this.Ig();this.W.O(this.l,"appresize",this.Ig);this.W.O(this.l,"onVideoAreaChange",this.Ig);this.W.O(this.l,"videodatachange",this.DO);this.W.O(this.l,"autonavchange",this.tB);this.W.O(this.l,"autonavcancel",this.AO);this.W.O(this.element,"transitionend",this.nU)};
g.h.destroy=function(){g.FF(this.W);g.af(this.B);this.B=[];this.C=null;b6.prototype.destroy.call(this);g.kq(this.element,"ytp-show-tiles");this.J.stop()};
g.h.Bx=function(){return 1!=this.D.autonavState};
g.h.show=function(){b6.prototype.show.call(this);g.kq(this.element,"ytp-show-tiles");g.Y(this.l).l?g.Zt(this.J):this.J.start();(this.I||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.RU(this.l,!1);j6(this)?(k6(this),2==this.D.autonavState?g.Y(this.l).experiments.g("fast_autonav_in_background")&&3==this.l.Ki()?g6(this.A,!0):d6(this.A):3==this.D.autonavState&&f6(this.A)):(g.RU(this.l,!0),k6(this))};
g.h.hide=function(){b6.prototype.hide.call(this);f6(this.A);k6(this)};
g.h.nU=function(a){g.rF(a)==this.element&&this.Ig()};
g.h.Ig=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.fV(this.K,!0),b=g.DH(this.K);b&&(b=b.qd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,D=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&D)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(D)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.cd(a.width/m||1,1,1.21);n*=g.cd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Hh(a,m,n);g.oh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});xAa(this.A,this.C[0]);g.U(this.element,"ytp-endscreen-takeover",j6(this));k6(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),p=g.dd(p+this.F,l),0!=r){v=this.B[c];v||(v=new h6(this.l),this.B[c]=v,a.appendChild(v.element));D=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-D-4,T=Math.floor(m*(f+r)/b)-H-4;g.vh(v.element,H,D);g.Hh(v.element,T,L);g.oh(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.C[p];r.A!=p&&(r.A=p,wAa(r,p,g.Y(r.l),g.iq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),v=(p=p.Md)&&p.itct)&&(p=r.l,g.Y(p).X&&(p=p.app.fa,r=r.element,D=r.getAttribute("data-visual-id"),g.Pa(p.g,r),g.pV(p,"onLogServerVeCreated",{id:D,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.B.length-1;b>=c;b--)e=this.B[b],g.Jd(e.element),g.$e(e);this.B.length=c}};
g.h.DO=function(){var a=this.l.getVideoData();this.D!=a&&(this.F=0,this.C=zAa(this,a),this.D=a,this.Ig())};
g.h.BO=function(){this.F+=this.B.length;this.Ig()};
g.h.CO=function(){this.F-=this.B.length;this.Ig()};
g.h.JL=function(){return!!this.A.A};
g.h.tB=function(a){1==a?(this.I=!1,this.H=this.D.clientPlaybackNonce,e6(this.A),this.o&&this.Ig()):(this.I=!0,this.o&&j6(this)&&(2==a?d6(this.A):3==a&&f6(this.A)))};
g.h.AO=function(a){if(a){for(a=0;a<this.B.length;a++)g.sV(this.K,this.B[a].element,!0);this.tB(1)}else this.H=null,this.I=!1;this.Ig()};
g.h.qu=function(){return this.o&&j6(this)};g.q(l6,g.tV);g.h=l6.prototype;g.h.UA=function(){var a=this.g.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!AAa(this.g)||b;a=g.LO(a,"ypc_module");var c=g.I0(this.g.app);return b&&!a&&!c};
g.h.TA=function(){return this.l.qu()};
g.h.FL=function(){return this.TA()?this.l.JL():!1};
g.h.V=function(){g.lV(this.g,"endscreen");g.tV.prototype.V.call(this)};
g.h.load=function(){g.tV.prototype.load.call(this);this.l.show()};
g.h.unload=function(){g.tV.prototype.unload.call(this);this.l.hide();this.l.destroy()};
g.h.DM=function(a){this.UA()&&(this.l.created||this.l.create(),"load"==a.getId()&&this.load())};
g.h.EM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.ND=function(){g.lV(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0);a=new g.iQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.iQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.iV(this.g,[a,b])};g.jY.endscreen=l6;})(_yt_player);
