(function(g){var window=this;var cBa=function(a,b){return g.Tb(a,b)},M6=function(a){g.Cm(a,"zx",g.xb());
return a},N6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Fm(a.g,b,c)},dBa=function(a,b){var c=[];
g.ok(b,function(a){try{var b=g.bD.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.aD(b)&&c.push(a):c.push(a)},a);
return c},eBa=function(a,b){var c=dBa(a,b);
(0,g.B)(c,function(a){g.bD.prototype.remove.call(this,a)},a)},fBa=function(a){if(a.yd){if(a.yd.locationOverrideToken)return{locationOverrideToken:a.yd.locationOverrideToken};
if(null!=a.yd.latitudeE7&&null!=a.yd.longitudeE7)return{latitudeE7:a.yd.latitudeE7,longitudeE7:a.yd.longitudeE7}}return null},gBa=function(a,b,c,d){var e=new g.tm(null,void 0);
a&&g.um(e,a);b&&g.vm(e,b);c&&g.wm(e,c);d&&g.xm(e,d);return e},hBa=function(a){g.RF[a]&&(a=g.RF[a],(0,g.B)(a,function(a){g.PF[a]&&delete g.PF[a]}),a.length=0)},iBa=function(a){var b=g.OF();
if(b)if(b.clear(a),a)hBa(a);else for(var c in g.RF)hBa(c)},O6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.nm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",jBa(this,a.capabilities||""),kBa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},jBa=function(a,b){a.capabilities.clear();
(0,g.Kd)(b.split(","),g.Fa(cBa,lBa)).forEach(function(b){a.capabilities.add(b)})},kBa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},P6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},Q6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},mBa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},nBa=function(a){return new P6(a)},oBa=function(a){return g.za(a)?(0,g.G)(a,nBa):[]},R6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},S6=function(a){return g.za(a)?"["+(0,g.G)(a,R6).join(",")+"]":"null"},T6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},pBa=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},U6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},V6=function(a,b){return g.La(a,function(a){return Q6(a,b)})},qBa=function(){var a=(0,g.KG)();
a&&eBa(a,a.g.Qd(!0))},W6=function(){var a=g.NG("yt-remote-connected-devices")||[];
g.gb(a);return a},rBa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},sBa=function(a){g.MG("yt-remote-connected-devices",a,86400)},Y6=function(){if(X6)return X6;
var a=g.NG("yt-remote-device-id");a||(a=T6(),g.MG("yt-remote-device-id",a,31536E3));for(var b=W6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return X6=d},Z6=function(){var a=W6(),b=Y6();
g.Pa(a,b);g.PG()&&g.jb(a,b);a=rBa(a);if(g.Qa(a))try{g.xG("remote_sid")}catch(c){}else try{g.wG("remote_sid",a.join(","),-1)}catch(c){}},tBa=function(){return g.NG("yt-remote-session-browser-channel")},uBa=function(){return g.NG("yt-remote-local-screens")||[]},vBa=function(){g.MG("yt-remote-lounge-token-expiration",!0,86400)},wBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(uBa(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.bm)(c,function(a){return!g.Pa(b,a)})&&vBa();
g.MG("yt-remote-local-screens",a,31536E3)},xBa=function(a,b){g.MG("yt-remote-session-browser-channel",a);
g.MG("yt-remote-session-screen-id",b);var c=W6(),d=Y6();g.Pa(c,d)||c.push(d);sBa(c);Z6()},$6=function(a){a||(g.OG("yt-remote-session-screen-id"),g.OG("yt-remote-session-video-id"));
Z6();a=W6();g.Ua(a,Y6());sBa(a)},yBa=function(){if(!a7){var a=g.mD();
a&&(a7=new g.WC(a))}return a7?!!a7.get("yt-remote-use-staging-server"):!1},zBa=function(){var a=window.document.createElement("a");
g.Zc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},ABa=function(a,b){var c=g.Dd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ad(c,g.be("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},BBa=function(){var a=zBa(),b=window.document.getElementById(a),c=b&&g.$E(b,"loaded");
c||b&&!c||(b=ABa(a,function(){g.$E(b,"loaded")||(g.ZE(b,"loaded","true"),g.VF(a),g.VD(g.Fa(iBa,a),0))}))},b7=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},CBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},c7=function(a){a.length?DBa(a.shift(),function(){c7(a)}):d7()},EBa=function(a){return"chrome-extension://"+a+e7},DBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},f7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},d7=function(){var a=CBa();
a&&a(!1,"No cast extension found")},g7=function(){if(FBa){var a=2,b=CBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;DBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",d7,c)}},GBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(g7(),a({command:"cast.sender.init"}))},HBa=function(){g7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);c7(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+e7,"//www.gstatic.com/eureka/clank"+e7])},h7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.pd=b;this.B=(0,g.z)(this.LJ,this);this.g=!1;this.l=0;this.o=this.Ba=null;this.A=[]},i7=function(){},j7=function(a,b,c,d){this.g=a;
this.o=b;this.D=c;this.C=d||1;this.A=45E3;this.W=new g.Jm(this);this.l=new g.rg;this.l.setInterval(250)},JBa=function(a,b,c){a.Kj=1;
a.mh=M6(b.clone());a.Ri=c;a.B=!0;IBa(a,null)},k7=function(a,b,c,d,e){a.Kj=1;
a.mh=M6(b.clone());a.Ri=null;a.B=c;e&&(a.WD=!1);IBa(a,d)},IBa=function(a,b){a.zk=(0,g.F)();
l7(a);a.Jh=a.mh.clone();N6(a.Jh,"t",a.C);a.Qm=0;a.Qc=a.g.Hr(a.g.Gm()?b:null);0<a.ws&&(a.Op=new g.Sk((0,g.z)(a.nF,a,a.Qc),a.ws));a.W.U(a.Qc,"readystatechange",a.hV);var c=a.mi?g.ac(a.mi):{};a.Ri?(a.Cq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Jh,a.Cq,a.Ri,c)):(a.Cq="GET",a.WD&&!g.zd&&(c.Connection="close"),a.Qc.send(a.Jh,a.Cq,null,c));a.g.Af(1)},MBa=function(a,b,c){for(var d=!0;!a.Wh&&a.Qm<c.length;){var e=KBa(a,c);
if(e==m7){4==b&&(a.nh=4,n7(15),d=!1);break}else if(e==LBa){a.nh=4;n7(16);d=!1;break}else o7(a,e)}4==b&&0==c.length&&(a.nh=1,n7(17),d=!1);a.Gf=a.Gf&&d;d||(p7(a),q7(a))},KBa=function(a,b){var c=a.Qm,d=b.indexOf("\n",c);
if(-1==d)return m7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return LBa;d+=1;if(d+c>b.length)return m7;var e=b.substr(d,c);a.Qm=d+c;return e},OBa=function(a,b){a.zk=(0,g.F)();
l7(a);var c=b?window.location.hostname:"";a.Jh=a.mh.clone();g.Cm(a.Jh,"DOMAIN",c);g.Cm(a.Jh,"t",a.C);try{a.Hf=new window.ActiveXObject("htmlfile")}catch(n){p7(a);a.nh=7;n7(22);q7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in r7)k=r7[l];else if(l in NBa)k=r7[l]=NBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=r7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.bd(g.uc("b/12014412"),d);a.Hf.open();a.Hf.write(g.Tc(c));a.Hf.close();a.Hf.parentWindow.m=(0,g.z)(a.qU,a);a.Hf.parentWindow.d=(0,g.z)(a.gD,a,!0);a.Hf.parentWindow.rpcClose=(0,g.z)(a.gD,a,!1);c=a.Hf.createElement("DIV");a.Hf.parentWindow.document.body.appendChild(c);d=g.Kc(a.Jh.toString());d=g.qb(g.Hc(d));d=g.bd(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Tc(d);
a.g.Af(1)},l7=function(a){a.Zv=(0,g.F)()+a.A;
PBa(a,a.A)},PBa=function(a,b){if(null!=a.Pk)throw Error("WatchDog timer not null");
a.Pk=s7((0,g.z)(a.GU,a),b)},t7=function(a){a.Pk&&(g.w.clearTimeout(a.Pk),a.Pk=null)},q7=function(a){a.g.nz()||a.Wh||a.g.Ap(a)},p7=function(a){t7(a);
g.$e(a.Op);a.Op=null;a.l.stop();g.Pm(a.W);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.Hf&&(a.Hf=null)},o7=function(a,b){try{a.g.ZC(a,b),a.g.Af(4)}catch(c){}},RBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;QBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){RBa(a,b,c,d,f)},f)})}},QBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{u7(d),c(!0)}catch(e){}};
d.onerror=function(){try{u7(d),c(!1)}catch(e){}};
d.onabort=function(){try{u7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{u7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},u7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},SBa=function(a){this.g=a;
this.l=new i7},TBa=function(a){var b=v7(a.g,a.Xk,"/mail/images/cleardot.gif");
M6(b);RBa(b.toString(),5E3,(0,g.z)(a.YI,a),3,2E3);a.Af(1)},x7=function(a){var b=a.g.H;
if(null!=b)n7(5),b?(n7(11),w7(a.g,a,!1)):(n7(12),w7(a.g,a,!0));else if(a.te=new j7(a,void 0,void 0,void 0),a.te.mi=a.ts,b=a.g,b=v7(b,b.Gm()?a.Cl:null,a.us),n7(5),!g.xd||g.qc(10))N6(b,"TYPE","xmlhttp"),k7(a.te,b,!1,a.Cl,!1);else{N6(b,"TYPE","html");var c=a.te;a=!!a.Cl;c.Kj=3;c.mh=M6(b.clone());OBa(c,a)}},y7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new i7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},UBa=function(a,b){this.g=a;
this.map=b;this.context=null},VBa=function(a){g.bf.call(this,"statevent",a)},WBa=function(a,b){g.bf.call(this,"timingevent",a);
this.size=b},XBa=function(a){g.bf.call(this,"serverreachability",a)},$Ba=function(a){YBa(a);
if(3==a.g){var b=a.km++,c=a.ko.clone();g.Cm(c,"SID",a.o);g.Cm(c,"RID",b);g.Cm(c,"TYPE","terminate");z7(a,c);b=new j7(a,a.o,b,void 0);b.Kj=2;b.mh=M6(c.clone());(new window.Image).src=b.mh;b.zk=(0,g.F)();l7(b)}ZBa(a)},aCa=function(a){a.tJ(1,0);
a.ko=v7(a,null,a.rs);A7(a)},YBa=function(a){a.ah&&(a.ah.abort(),a.ah=null);
a.tc&&(a.tc.cancel(),a.tc=null);a.sg&&(g.w.clearTimeout(a.sg),a.sg=null);B7(a);a.Wd&&(a.Wd.cancel(),a.Wd=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},bCa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new UBa(a.aQ++,b));2!=a.g&&3!=a.g||A7(a)},A7=function(a){a.Wd||a.eh||(a.eh=s7((0,g.z)(a.eD,a),0),a.zj=0)},dCa=function(a,b){if(1==a.g){if(!b){a.km=Math.floor(1E5*Math.random());
var c=a.km++,d=new j7(a,"",c,void 0);d.mi=null;var e=C7(a),f=a.ko.clone();g.Cm(f,"RID",c);g.Cm(f,"CVER","1");z7(a,f);JBa(d,f,e);a.Wd=d;a.g=2}}else 3==a.g&&(b?cCa(a,b):0==a.l.length||a.Wd||cCa(a))},cCa=function(a,b){if(b)if(6<a.Yh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.km-1;var d=C7(a)}else c=b.D,d=b.Ri;else c=a.km++,d=C7(a);var e=a.ko.clone();g.Cm(e,"SID",a.o);g.Cm(e,"RID",c);g.Cm(e,"AID",a.Yj);z7(a,e);c=new j7(a,a.o,c,a.zj+1);c.mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Wd=c;JBa(c,e,d)},z7=function(a,b){if(a.od){var c=a.od.Ty();
c&&g.Jb(c,function(a,c){g.Cm(b,c,a)})}},C7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Yh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Yh?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},eCa=function(a){a.tc||a.sg||(a.D=1,a.sg=s7((0,g.z)(a.dD,a),0),a.mj=0)},D7=function(a){if(a.tc||a.sg||3<=a.mj)return!1;
a.D++;a.sg=s7((0,g.z)(a.dD,a),fCa(a,a.mj));a.mj++;return!0},w7=function(a,b,c){a.Bq=c;
a.Uf=b.Dg;a.C||aCa(a)},B7=function(a){null!=a.bi&&(g.w.clearTimeout(a.bi),a.bi=null)},fCa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},E7=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.z)(a.ZV,a);c||(c=new g.tm("//www.google.com/images/cleardot.gif"),M6(c));QBa(c.toString(),1E4,d)}else n7(2);gCa(a,b)},gCa=function(a,b){a.g=0;
a.od&&a.od.Mx(b);ZBa(a);YBa(a)},ZBa=function(a){a.g=0;
a.Uf=-1;if(a.od)if(0==a.A.length&&0==a.l.length)a.od.ur();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.od.ur(b)}},v7=function(a,b,c){var d=g.Dm(c);
if(""!=d.l)b&&g.vm(d,b+"."+d.l),g.wm(d,d.B);else{var e=window.location;d=gBa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ol&&g.Jb(a.ol,function(a,b){g.Cm(d,b,a)});
g.Cm(d,"VER",a.Yh);z7(a,d);return d},s7=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},n7=function(a){F7.dispatchEvent(new VBa(F7,a))},hCa=function(){},iCa=function(a,b){this.action=a;
this.params=b||{}},G7=function(a,b){g.M.call(this);
this.g=new g.Xt(this.hU,0,this);g.N(this,this.g);this.pd=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},H7=function(a,b,c){this.J=a;
this.C=b;this.o=new g.VC;this.l=new G7(this.IW,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.K=c||!1},jCa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Bq,sessionId:a.g.o,arrayId:a.g.Yj}},kCa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&dCa(a.g),$Ba(a.g));a.F=0},I7=function(a){return!!a.g&&3==a.g.g},lCa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},J7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},K7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},L7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.A,d,!0),onError:g.Fa(a.o,e),ud:g.Fa(a.B,e)};c&&(a.Mb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.lE(b,a)},pCa=function(){var a=mCa;
nCa();M7.push(a);oCa(M7)},N7=function(a,b){nCa();
var c=M7,d=qCa(a,String(b));g.Qa(c)?rCa(d):(oCa(c),(0,g.B)(c,function(a){a(d)}))},nCa=function(){M7||(M7=g.x("yt.mdx.remote.debug.handlers_")||[],g.wa("yt.mdx.remote.debug.handlers_",M7,void 0))},rCa=function(a){var b=(O7+1)%50;
O7=b;P7[b]=a;Q7||(Q7=49==b)},oCa=function(a){var b=P7;
if(b[0]){var c=O7,d=Q7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
P7=Array(50);O7=-1;Q7=!1}},qCa=function(a,b){var c=((0,g.F)()-sCa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},R7=function(a){g.GF.call(this);
this.D=a;this.g=[]},tCa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},uCa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Kd)(a.g,function(a){return!!U6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=tCa(a,b[d])||c;return c},vCa=function(a,b){var c=a.g.length;
a.g=(0,g.Kd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},S7=function(a,b,c,d){g.GF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Ba=window.NaN},U7=function(a){R7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;T7(this);this.info("Initializing with "+S6(this.g))},wCa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=K7(a.o,"/pairing/get_lounge_token_batch");
L7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.YJ,a),(0,g.z)(a.XJ,a))}},T7=function(a){var b=oBa(uBa());
b=(0,g.Kd)(b,function(a){return!a.uuid});
return uCa(a,b)},V7=function(a,b){wBa((0,g.G)(a.g,mBa));
b&&vBa()},X7=function(a,b){g.GF.call(this);
this.C=b;var c=g.NG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;W7("Initialized with "+g.yg(this.g))},xCa=function(a,b,c){var d=K7(a.B,"/pairing/get_screen_availability");
L7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},Y7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(W7("Updated online screens: "+g.yg(a.g)),a.g=b,a.R("screenChange"));yCa(a)},Z7=function(a){(0,window.isNaN)(a.o)||g.XD(a.o);
a.o=g.VD((0,g.z)(a.lv,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},W7=function(a){N7("OnlineScreenService",a)},zCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.fc("Requesting availability of screen w/o lounge token.")});
return b},yCa=function(a){a=g.Qb(g.Kb(a.g,function(a){return a}));
g.gb(a);a.length?g.MG("yt-remote-online-screen-ids",a.join(","),60):g.OG("yt-remote-online-screen-ids")},$7=function(a){R7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};ACa(this)},CCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?V6(k,c):null)||V6(k,b)){k.uuid=b;var l=a8(a,k);xCa(a.l,l,function(a){e(a?l:null)})}else c?BCa(a,c,(0,g.z)(function(a){var f=a8(this,new P6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));xCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},DCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},BCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Mb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.lE(K7(a.C,"/pairing/get_lounge_token_batch"),e)},ECa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+S6(a.g))},ACa=function(a){b8(a);
a.o=new U7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.nK,a));ECa(a);a.A=oBa(g.NG("yt-remote-automatic-screen-cache")||[]);b8(a);a.info("Initializing automatic screens: "+S6(a.A));a.l=new X7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.R("onlineScreenChange")},a))},a8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=V6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.MG("yt-remote-automatic-screen-cache",(0,g.G)(a.A,mBa)));b8(a);a.B[b.uuid]=b.id;g.MG("yt-remote-device-id-map",a.B,31536E3);return b},b8=function(a){a.B=g.NG("yt-remote-device-id-map")||{}},c8=function(a,b,c){g.GF.call(this);
this.K=c;this.H=a;this.l=b;this.o=null},d8=function(a,b){N7(a.K,b)},e8=function(a,b){c8.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.OW,this);this.B=(0,g.z)(this.SU,this);this.A=g.VD((0,g.z)(function(){FCa(this,null)},this),12E4)},GCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){d8(this,"Failed to send message: getMdxSessionStatus.")},a)):d8(a,"Sending yt message without session: "+g.yg(b))},FCa=function(a,b){g.XD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Bp,a),d=(0,g.z)(a.re,a);a.ez(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},f8=function(a,b,c){c8.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.M=c;this.B=null;this.D=g.y;this.C=window.NaN;this.J=(0,g.z)(this.RW,this);this.g=g.y},HCa=function(a){a.g=a.H.uF(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Bp(a)},a),(0,g.z)(function(a){this.g=g.y;
this.re(a)},a))},ICa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.M;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}yBa()&&(b.env_useStageMdx=1);return g.Og(b)},g8=function(a,b){c8.call(this,a,b,"ManualSession");
this.g=g.VD((0,g.z)(this.ak,this,null),150)},h8=function(a,b,c,d){g.GF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.qT,this)},JCa=function(a,b){return b?g.La(a.o,function(a){return Q6(b,a.label)},a):null},i8=function(a){N7("Controller",a)},mCa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},j8=function(a){return a.B||!!a.o.length||!!a.g},k8=function(a,b,c){b!=a.g&&(g.$e(a.g),(a.g=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.l):a.R("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.bD,a,b)),b.o?a.R("yt-remote-cast2-session-change",b.o):c&&a.g.ak(null)):a.R("yt-remote-cast2-session-change",null))},KCa=function(a){var b=a.l.tF(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&Q6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=JCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},QCa=function(a,b,c,d,e,f,k){LCa()?MCa(b,e,f,k)&&(m8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?NCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?NCa(a,c):(n8("Failed to load cast API: "+d),o8(!1),m8(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),OCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):BBa():f7("CriOS")?GBa():f7("Android")&&f7("Chrome/")&&window.navigator.presentation?HBa():window.chrome&&window.navigator.presentation&&!f7("Edge")?(g7(),c7(PCa.map(EBa))):d7())):l8("Cannot initialize because not running Chrome")},OCa=function(){l8("dispose");
var a=p8();a&&a.dispose();g.wa("yt.mdx.remote.cloudview.instance_",null,void 0);RCa(!1);g.TF(q8);q8.length=0},r8=function(){return!!g.NG("yt-remote-cast-installed")},SCa=function(){var a=g.NG("yt-remote-cast-receiver");
return a?a.friendlyName:null},TCa=function(){l8("clearCurrentReceiver");
g.OG("yt-remote-cast-receiver")},UCa=function(){return r8()?p8()?p8().getCastSession():(n8("getCastSelector: Cast is not initialized."),null):(n8("getCastSelector: Cast API is not installed!"),null)},t8=function(){r8()?p8()?s8()?(l8("Requesting cast selector."),p8().requestSession()):(l8("Wait for cast API to be ready to request the session."),q8.push(g.SF("yt-remote-cast2-api-ready",t8))):n8("requestCastSelector: Cast is not initialized."):n8("requestCastSelector: Cast API is not installed!")},u8=
function(a,b){s8()?p8().setConnectedScreenStatus(a,b):n8("setConnectedScreenStatus called before ready.")},LCa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.yI||a},VCa=function(a,b){p8().init(a,b)},MCa=function(a,b,c,d){var e=!1;
p8()||(a=new h8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.MG("yt-remote-cast-available",a);g.WF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){l8("onReceiverSelected: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a);g.WF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){l8("onReceiverResumed: "+a.friendlyName);
g.MG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){l8("onSessionChange: "+R6(a));
a||g.OG("yt-remote-cast-receiver");g.WF("yt-remote-cast2-session-change",a)}),g.wa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
l8("cloudview.createSingleton_: "+e);return e},p8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},NCa=function(a,b){o8(!0);
m8(!1);VCa(a,function(a){a?(RCa(!0),g.VF("yt-remote-cast2-api-ready")):(n8("Failed to initialize cast API."),o8(!1),g.OG("yt-remote-cast-available"),g.OG("yt-remote-cast-receiver"),OCa());b(a)})},l8=function(a){N7("cloudview",a)},n8=function(a){N7("cloudview",a)},o8=function(a){l8("setCastInstalled_ "+a);
g.MG("yt-remote-cast-installed",a)},s8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},RCa=function(a){l8("setApiReady_ "+a);
g.wa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m8=function(a){g.wa("yt.mdx.remote.cloudview.initializing_",a,void 0)},v8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Xf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},w8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Xf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.F)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},x8=function(a){return a.kb()?((0,g.F)()-a.D)/1E3:0},y8=function(a,b){a.F=b;
a.D=(0,g.F)()},z8=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},A8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w8(a)},B8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.l);b.hasPrevious=a.Xf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},D8=function(a,b){g.GF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.lC;this.o=this.l=null;this.H=(0,g.z)(this.KQ,this);this.D=(0,g.z)(this.qm,this);this.F=(0,g.z)(this.JQ,this);this.I=(0,g.z)(this.WQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hw,this),WCa(this))):c=3;0!=c&&(b?this.hw(c):g.VD((0,g.z)(function(){this.hw(c)},this),0));
var d=UCa();d&&C8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},E8=function(a){return new v8(a.A.getPlayerContextData())},WCa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Fa(this.lT,a),this))},a)},XCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},F8=function(a,b){50>a.B.Cc()&&g.nC(a.B,b)},H8=function(a,b,c){var d=E8(a);
y8(d,c);-1E3!=d.g&&(d.g=b);G8(a,d)},I8=function(a,b,c){a.A.sendMessage(b,c)},G8=function(a,b){XCa(a);
a.A.setPlayerContextData(B8(b));WCa(a)},C8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.qm(null));
a.o=b;a.o&&(N7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.qm(a.o.media[0]))},YCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=E8(a);b.contentId!=d.videoId&&N7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;y8(d,a.l.getEstimatedTime());G8(a,d)}else N7("CP","No cast media video. Ignoring state update.")},J8=function(a,b,c){return(0,g.z)(function(a){this.fc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.fc("Retrying "+b+" using MDx browser channel."),I8(this,b,c))},a)},K8=function(a,b,c){g.GF.call(this);
this.B=window.NaN;this.M=!1;this.I=this.H=this.J=this.K=window.NaN;this.T=[];this.A=this.D=this.o=this.Za=this.g=null;this.ra=a;this.T.push(g.pF(window,"beforeunload",(0,g.z)(this.PJ,this)));this.l=[];this.Za=new v8;this.Z=b.id;this.g=ZCa(this,c);this.g.subscribe("handlerOpened",this.OQ,this);this.g.subscribe("handlerClosed",this.LQ,this);this.g.subscribe("handlerError",this.MQ,this);this.g.subscribe("handlerMessage",this.NQ,this);lCa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.PG()&&g.MG("yt-remote-session-video-id",a)},this)},L8=function(a){N7("conn",a)},ZCa=function(a,b){return new H7(K7(a.ra,"/bc"),b)},M8=function(a,b){a.R("proxyStateChange",b)},$Ca=function(a){a.B=g.VD((0,g.z)(function(){L8("Connecting timeout");
this.C(1)},a),2E4)},N8=function(a){g.XD(a.B);
a.B=window.NaN},O8=function(a){g.XD(a.K);
a.K=window.NaN},aDa=function(a){P8(a);
a.J=g.VD((0,g.z)(function(){Q8(this,"getNowPlaying")},a),2E4)},P8=function(a){g.XD(a.J);
a.J=window.NaN},cDa=function(a,b){b&&(N8(a),O8(a));
b==(I7(a.g)&&(0,window.isNaN)(a.B))?b&&(M8(a,1),Q8(a,"getSubtitlesTrack")):b?(a.X()&&a.Za.reset(),M8(a,1),Q8(a,"getNowPlaying"),bDa(a)):a.C(1)},dDa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Wb(b.params)?a.Za.l=null:a.Za.l=b.params,a.R("remotePlayerChange"))},eDa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;A8(a.Za,c,d);a.R("remoteQueueChange")},gDa=function(a,b){b.params=b.params||{};
eDa(a,b);fDa(a,b);a.R("autoplayDismissed")},fDa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
y8(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?aDa(a):P8(a);
a.R("remotePlayerChange")},hDa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);y8(a.Za,(0,window.isNaN)(c)?0:c);a.R("remotePlayerChange")}},iDa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.R("remotePlayerChange")},jDa=function(a,b){a.D=b.params.videoId;
a.R("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},kDa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Xf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.R("previousNextChange")},bDa=function(a){g.XD(a.I);
a.I=g.VD((0,g.z)(a.C,a,1),864E5)},Q8=function(a,b,c){c?L8("Sending: action="+b+", params="+g.yg(c)):L8("Sending: action="+b);
a.g.sendMessage(b,c)},R8=function(a){R7.call(this,"ScreenServiceProxy");
this.ed=a;this.l=[];this.l.push(this.ed.$_s("screenChange",(0,g.z)(this.MW,this)));this.l.push(this.ed.$_s("onlineScreenChange",(0,g.z)(this.MS,this)))},pDa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.PD("MDX_CONFIG")||b;qBa();Z6();S8||(S8=new J7(b?b.loungeApiHost:void 0),yBa()&&(S8.g="/api/loungedev"));T8||(T8=g.x("yt.mdx.remote.deferredProxies_")||[],g.wa("yt.mdx.remote.deferredProxies_",T8,void 0));lDa();var c=U8();if(!c){var d=new $7(S8);g.wa("yt.mdx.remote.screenService_",d,void 0);c=U8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);QCa(a,d,function(a){a?V8()&&u8(V8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.WF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.wa("yt.mdx.remote.initialized_",!0,void 0),W8("Initializing: "+g.yg(b)),X8.push(g.SF("yt-remote-cast2-availability-change",function(){g.WF("yt-remote-receiver-availability-change")})),X8.push(g.SF("yt-remote-cast2-receiver-selected",function(){Y8(null);
g.WF("yt-remote-auto-connect","cast-selector-receiver")})),X8.push(g.SF("yt-remote-cast2-receiver-resumed",function(){g.WF("yt-remote-receiver-resumed","cast-selector-receiver")})),X8.push(g.SF("yt-remote-cast2-session-change",mDa)),X8.push(g.SF("yt-remote-connection-change",function(a){a?u8(V8(),"YouTube TV"):Z8()||(u8(null,null),TCa())})),a=$8(),b.isAuto&&(a.id+="#dial"),g.MF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),W8(" -- with channel params: "+
g.yg(a)),nDa(a),c.start(),V8()||oDa())},rDa=function(){var a=qDa();
r8()&&g.NG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},qDa=function(){var a=U8().ed.$_gos();
var b=a9();b&&b9()&&(U6(a,b)||a.push(b));return pBa(a)},c9=function(){var a=sDa();
!a&&r8()&&SCa()&&(a={key:"cast-selector-receiver",name:SCa()});return a},sDa=function(){var a=qDa(),b=a9();
b||(b=Z8());return g.La(a,function(a){return b&&Q6(b,a.key)?!0:!1})},a9=function(){var a=V8();
if(!a)return null;var b=U8().ke();return V6(b,a)},mDa=function(a){W8("remote.onCastSessionChange_: "+R6(a));
if(a){var b=a9();b&&b.id==a.id?u8(b.id,"YouTube TV"):(b&&d9(),e9(a,1))}else b9()&&d9()},d9=function(){s8()?p8().stopSession():n8("stopSession called before API ready.");
var a=b9();a&&(a.disconnect(1),f9(null))},g9=function(){var a=b9();
return!!a&&3!=a.getProxyState()},W8=function(a){N7("remote",a)},U8=function(){if(!h9){var a=g.x("yt.mdx.remote.screenService_");
h9=a?new R8(a):null}return h9},V8=function(){return g.x("yt.mdx.remote.currentScreenId_")},tDa=function(a){g.wa("yt.mdx.remote.currentScreenId_",a,void 0)},uDa=function(){return g.x("yt.mdx.remote.connectData_")},Y8=function(a){g.wa("yt.mdx.remote.connectData_",a,void 0)},b9=function(){return g.x("yt.mdx.remote.connection_")},f9=function(a){var b=b9();
Y8(null);a||tDa("");g.wa("yt.mdx.remote.connection_",a,void 0);T8&&((0,g.B)(T8,function(b){b(a)}),T8.length=0);
b&&!a?g.WF("yt-remote-connection-change",!1):!b&&a&&g.WF("yt-remote-connection-change",!0)},Z8=function(){var a=g.PG();
if(!a)return null;var b=U8().ke();return V6(b,a)},e9=function(a,b){a9()&&a9();
tDa(a.id);var c=new K8(S8,a,$8());c.connect(b,uDa());c.subscribe("beforeDisconnect",function(a){g.WF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){b9()&&f9(null)});
f9(c)},oDa=function(){var a=Z8();
a?(W8("Resume connection to: "+R6(a)),e9(a,0)):($6(),TCa(),W8("Skipping connecting because no session screen found."))},lDa=function(){var a=$8();
if(g.Wb(a)){a=Y6();var b=g.NG("yt-remote-session-name")||"",c=g.NG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.wa("yt.mdx.remote.channelParams_",a,void 0)}},$8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},nDa=function(a){a?(g.MG("yt-remote-session-app",a.app),g.MG("yt-remote-session-name",a.name)):(g.OG("yt-remote-session-app"),g.OG("yt-remote-session-name"));
g.wa("yt.mdx.remote.channelParams_",a,void 0)},i9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.DF(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.dS);this.o.O(b,"captionschanged",this.IQ);this.o.O(b,"captionssettingschanged",this.HE);this.o.O(b,"videoplayerreset",this.Cp);this.o.O(b,"mdxautoplaycancel",this.XI);this.T=this.o.O(b,"onVolumeChange",this.LC);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.YC,this);c.subscribe("remotePlayerChange",this.tm,this);c.subscribe("remoteQueueChange",this.Cp,this);c.subscribe("autoplayUpNext",this.wC,
this);c.subscribe("previousNextChange",this.VC,this);c.subscribe("nowAutoplaying",this.NC,this);c.subscribe("autoplayDismissed",this.vC,this);this.suggestion=null;this.H=new g.uP(64);this.A=new g.Xt(this.DE,500,this);g.N(this,this.A);this.B=new g.Xt(this.EE,1E3,this);g.N(this,this.B);this.J=new h7(this.oW,0,this);g.N(this,this.J);this.C={};this.K=new g.Xt(this.dF,1E3,this);g.N(this,this.K);this.I=new g.Sk(this.HO,1E3,this);g.N(this,this.I);this.M=g.y;this.HE();this.Cp();this.tm()},j9=function(a,b){var c=
a.F,d=a.l.getVideoData().lengthSeconds;
c.H=b||0;c.g.R("progresssync",b,d)},vDa=function(a){j9(a,0);
a.A.stop();k9(a,new g.uP(64))},m9=function(a,b){if(l9(a)&&!a.D){var c=null;
b&&(c={style:a.l.Ji()},g.dc(c,b));a.g.rE(a.l.getVideoData(1).videoId,c);a.C=E8(a.g).l}},n9=function(a,b){var c=a.l.eg();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Tj;f=fBa(f);var n=E8(c);l=l||0;var p={videoId:k,currentIndex:l};A8(n,k,l);g.t(b)&&(y8(n,b),p.currentTime=b);g.t(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.yg(f));I8(c,"setPlaylist",p);e||G8(c,n);k9(a,new g.uP(1))},wDa=function(a,b){if(b){var c=a.l.xc("captions","tracklist",{aA:1});
c&&c.length?(a.l.Kd("captions","track",b),a.D=!1):(a.l.ik("captions"),a.D=!0)}else a.l.Kd("captions","track",{})},l9=function(a){return E8(a.g).videoId==a.l.getVideoData(1).videoId},k9=function(a,b){a.B.stop();
var c=a.H;if(!g.zP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.YU(a.l,d);a.H=b;xDa(a.F,c,b)}},o9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",N:[{G:"div",L:"ytp-remote-display-status",N:[{G:"div",L:"ytp-remote-display-status-icon",N:[g.$oa()]},{G:"div",L:"ytp-remote-display-status-text",aa:"{{statustext}}"}]}]});this.l=new g.NV(this,250);g.N(this,this.l);this.A=a;this.O(a,"presentingplayerstatechange",this.B);yDa(this,g.VU(a))},yDa=function(a,b){if(3==a.A.Pa()){var c={RECEIVER_NAME:a.A.xc("remote","currentReceiver").name};
c=g.X(b,128)?g.O0("Error on $RECEIVER_NAME",c):b.kb()||g.X(b,4)?g.O0("Playing on $RECEIVER_NAME",c):g.O0("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},p9=function(a,b){g.WZ.call(this,"Play on",0,a,b);
this.l=a;this.H={};this.O(a,"onMdxReceiversChange",this.J);this.O(a,"presentingplayerstatechange",this.J);this.J()},q9=function(a){g.tV.call(this,a);
this.o={key:T6(),name:"This computer"};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.uP(64);this.H=0;if(!g.RM(g.Y(this.g))){a=this.g;var b=g.DH(a);b&&(b=b.Xo())&&(b=new p9(a,b),g.N(this,b));b=new o9(a);g.N(this,b);g.nV(a,b.element,4)}},xDa=function(a,b,c){a.D=c;
a.g.R("presentingplayerstatechange",new g.EP(c,b))},r9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)d9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.getVideoData(1);var e=d.videoId;if(c||e){var f=a.g.eg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Tj,index:Math.max(a.g.cB(),0),currentTime:0==f?void 0:f};(d=fBa(d))&&(c.locationInfo=d);d=c}else d=null;W8("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(Y8(d||null),s8()?p8().setLaunchParams(d||null):
n8("setLaunchParams called before ready.")):!d&&g9()&&V8()==b.key?g.WF("yt-remote-connection-change",!0):(d9(),Y8(d||null),d=U8().ke(),(d=V6(d,b.key))&&e9(d,1))}},NBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},r7={"'":"\\'"},zDa={},lBa={cY:"atp",E2:"ska",S1:"que",b1:"mus",A2:"sus",k_:"dsp"};
O6.prototype.Qn=function(){var a=new O6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var a7,X6="",e7=b7("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",FBa=b7("loadCastFramework")||b7("loadCastApplicationFramework"),PCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(h7,g.M);g.h=h7.prototype;g.h.KJ=function(a){this.A=arguments;this.g=!1;this.Ba?this.o=(0,g.F)()+this.pd:this.Ba=g.sg(this.B,this.pd)};
g.h.stop=function(){this.Ba&&(g.tg(this.Ba),this.Ba=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.V=function(){this.stop();h7.ba.V.call(this)};
g.h.LJ=function(){this.o?(this.Ba=g.sg(this.B,this.o-(0,g.F)()),this.o=null):(this.Ba=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};i7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
i7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=j7.prototype;g.h.mi=null;g.h.Gf=!1;g.h.Pk=null;g.h.Zv=null;g.h.zk=null;g.h.Kj=null;g.h.mh=null;g.h.Jh=null;g.h.Ri=null;g.h.Qc=null;g.h.Qm=0;g.h.Hf=null;g.h.Cq=null;g.h.nh=null;g.h.Dl=-1;g.h.WD=!0;g.h.Wh=!1;g.h.ws=0;g.h.Op=null;var LBa={},m7={};g.h=j7.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.hV=function(a){a=a.target;var b=this.Op;b&&3==g.hx(a)?b.Ij():this.nF(a)};
g.h.nF=function(a){try{if(a==this.Qc)a:{var b=g.hx(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.xd&&!g.qc(10)||g.zd&&!g.pc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.df&&!g.lx(this.Qc))break a;this.Wh||4!=b||7==c||(8==c||0>=d?this.g.Af(3):this.g.Af(2));t7(this);var e=this.Qc.getStatus();this.Dl=e;var f=g.lx(this.Qc);(this.Gf=200==e)?(4==b&&p7(this),this.B?(MBa(this,b,f),g.df&&this.Gf&&3==b&&(this.W.U(this.l,"tick",this.dV),this.l.start())):o7(this,f),this.Gf&&!this.Wh&&(4==b?this.g.Ap(this):
(this.Gf=!1,l7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.nh=3,n7(13)):(this.nh=0,n7(14)),p7(this),q7(this))}}catch(k){this.Qc&&g.lx(this.Qc)}finally{}};
g.h.dV=function(){var a=g.hx(this.Qc),b=g.lx(this.Qc);this.Qm<b.length&&(t7(this),MBa(this,a,b),this.Gf&&4!=a&&l7(this))};
g.h.qU=function(a){s7((0,g.z)(this.pU,this,a),0)};
g.h.pU=function(a){this.Wh||(t7(this),o7(this,a),l7(this))};
g.h.gD=function(a){s7((0,g.z)(this.oU,this,a),0)};
g.h.oU=function(a){this.Wh||(p7(this),this.Gf=a,this.g.Ap(this),this.g.Af(4))};
g.h.cancel=function(){this.Wh=!0;p7(this)};
g.h.GU=function(){this.Pk=null;var a=(0,g.F)();0<=a-this.Zv?(2!=this.Kj&&this.g.Af(3),p7(this),this.nh=2,n7(18),q7(this)):PBa(this,this.Zv-a)};g.h=SBa.prototype;g.h.ts=null;g.h.te=null;g.h.Pp=!1;g.h.oz=null;g.h.eo=null;g.h.Ct=null;g.h.us=null;g.h.Me=null;g.h.Dg=-1;g.h.Cl=null;g.h.Xk=null;g.h.connect=function(a){this.us=a;a=v7(this.g,null,this.us);n7(3);this.oz=(0,g.F)();var b=this.g.F;null!=b?(this.Cl=b[0],(this.Xk=b[1])?(this.Me=1,TBa(this)):(this.Me=2,x7(this))):(N6(a,"MODE","init"),this.te=new j7(this,void 0,void 0,void 0),this.te.mi=this.ts,k7(this.te,a,!1,null,!0),this.Me=0)};
g.h.YI=function(a){if(a)this.Me=2,x7(this);else{n7(4);var b=this.g;b.Uf=b.ah.Dg;E7(b,9)}a&&this.Af(2)};
g.h.Hr=function(a){return this.g.Hr(a)};
g.h.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.Dg=-1};
g.h.nz=function(){return!1};
g.h.ZC=function(a,b){this.Dg=a.Dl;if(0==this.Me)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Uf=this.Dg;E7(c,2);return}this.Cl=c[0];this.Xk=c[1]}else c=this.g,c.Uf=this.Dg,E7(c,2);else if(2==this.Me)if(this.Pp)n7(7),this.Ct=(0,g.F)();else if("11111"==b){if(n7(6),this.Pp=!0,this.eo=(0,g.F)(),c=this.eo-this.oz,!g.xd||g.qc(10)||500>c)this.Dg=200,this.te.cancel(),n7(12),w7(this.g,this,!0)}else n7(8),this.eo=this.Ct=(0,g.F)(),this.Pp=!1};
g.h.Ap=function(){this.Dg=this.te.Dl;if(this.te.Gf)0==this.Me?this.Xk?(this.Me=1,TBa(this)):(this.Me=2,x7(this)):2==this.Me&&((!g.xd||g.qc(10)?!this.Pp:200>this.Ct-this.eo)?(n7(11),w7(this.g,this,!1)):(n7(12),w7(this.g,this,!0)));else{0==this.Me?n7(9):2==this.Me&&n7(10);var a=this.g;a.Uf=this.Dg;E7(a,2)}};
g.h.Gm=function(){return this.g.Gm()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Af=function(a){this.g.Af(a)};g.h=y7.prototype;g.h.ol=null;g.h.Wd=null;g.h.tc=null;g.h.rs=null;g.h.ko=null;g.h.Cx=null;g.h.xo=null;g.h.km=0;g.h.aQ=0;g.h.od=null;g.h.eh=null;g.h.sg=null;g.h.bi=null;g.h.ah=null;g.h.Bq=null;g.h.Yj=-1;g.h.qA=-1;g.h.Uf=-1;g.h.zj=0;g.h.mj=0;g.h.Yh=8;var F7=new g.Df;g.A(VBa,g.bf);g.A(WBa,g.bf);g.A(XBa,g.bf);g.h=y7.prototype;g.h.connect=function(a,b,c,d,e){n7(0);this.rs=b;this.ol=c||{};d&&g.t(e)&&(this.ol.OSID=d,this.ol.OAID=e);this.C?(s7((0,g.z)(this.Xx,this,a),100),aCa(this)):this.Xx(a)};
g.h.Xx=function(a){this.ah=new SBa(this);this.ah.ts=null;this.ah.l=this.B;this.ah.connect(a)};
g.h.nz=function(){return 0==this.g};
g.h.eD=function(a){this.eh=null;dCa(this,a)};
g.h.dD=function(){this.sg=null;this.tc=new j7(this,this.o,"rpc",this.D);this.tc.mi=null;this.tc.ws=0;var a=this.Cx.clone();g.Cm(a,"RID","rpc");g.Cm(a,"SID",this.o);g.Cm(a,"CI",this.Bq?"0":"1");g.Cm(a,"AID",this.Yj);z7(this,a);if(!g.xd||g.qc(10))g.Cm(a,"TYPE","xmlhttp"),k7(this.tc,a,!0,this.xo,!1);else{g.Cm(a,"TYPE","html");var b=this.tc,c=!!this.xo;b.Kj=3;b.mh=M6(a.clone());OBa(b,c)}};
g.h.ZC=function(a,b){if(0!=this.g&&(this.tc==a||this.Wd==a))if(this.Uf=a.Dl,this.Wd==a&&3==this.g)if(7<this.Yh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.sg){if(this.tc)if(this.tc.zk+3E3<this.Wd.zk)B7(this),this.tc.cancel(),this.tc=null;else break a;D7(this);n7(19)}}else this.qA=c[1],0<this.qA-this.Yj&&37500>c[2]&&this.Bq&&0==this.mj&&!this.bi&&(this.bi=s7((0,g.z)(this.DQ,this),6E3));else E7(this,11)}else b!=zDa.fZ.g&&E7(this,11);else if(this.tc==a&&
B7(this),!g.C(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.xo=e[2],e=e[3],null!=e?this.Yh=e:this.Yh=6,this.g=3,this.od&&this.od.Ox(),this.Cx=v7(this,this.Gm()?this.xo:null,this.rs),eCa(this)):"stop"==e[0]&&E7(this,7):3==this.g&&("stop"==e[0]?E7(this,7):"noop"!=e[0]&&this.od&&this.od.Nx(e),this.mj=0)}}};
g.h.DQ=function(){null!=this.bi&&(this.bi=null,this.tc.cancel(),this.tc=null,D7(this),n7(20))};
g.h.Ap=function(a){if(this.tc==a){B7(this);this.tc=null;var b=2}else if(this.Wd==a)this.Wd=null,b=1;else return;this.Uf=a.Dl;if(0!=this.g)if(a.Gf)1==b?(b=(0,g.F)()-a.zk,F7.dispatchEvent(new WBa(F7,a.Ri?a.Ri.length:0,b,this.zj)),A7(this),this.A.length=0):eCa(this);else{var c=a.nh,d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.Wd||this.eh||1==this.g||2<=this.zj?d=!1:(this.eh=s7((0,g.z)(this.eD,this,a),fCa(this,this.zj)),this.zj++,d=!0);d=!(d||2==b&&D7(this))}if(d)switch(c){case 1:E7(this,5);
break;case 4:E7(this,10);break;case 3:E7(this,6);break;case 7:E7(this,12);break;default:E7(this,2)}}};
g.h.tJ=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.ZV=function(a){a?n7(2):(n7(1),gCa(this,8))};
g.h.Hr=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.bx;a.F=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.Af=function(a){F7.dispatchEvent(new XBa(F7,a))};
g.h.Gm=function(){return!(!g.xd||g.qc(10))};
g.h=hCa.prototype;g.h.Ox=function(){};
g.h.Nx=function(){};
g.h.Mx=function(){};
g.h.ur=function(){};
g.h.Ty=function(){return{}};
g.h.isActive=function(){return!0};g.A(G7,g.M);g.h=G7.prototype;g.h.hU=function(){this.pd=Math.min(3E5,2*this.pd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.pd+15E3*Math.random();g.Yt(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.pd=5E3};g.A(H7,hCa);g.h=H7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Pd=function(a){return this.o.Pd(a)};
g.h.R=function(a,b){return this.o.R.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.$e(this.o),kCa(this),g.$e(this.l),this.l=null)};
g.h.ka=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new y7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.K),e=this.g;e&&(e.od=null);d.od=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Yj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):I7(this)&&bCa(this.g,c)};
g.h.Ox=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)bCa(this.g,a[b])}this.R("handlerOpened")};
g.h.Mx=function(a){var b=2==a&&401==this.g.Uf;4==a||b||this.l.start();this.R("handlerError",a)};
g.h.ur=function(a){if(!this.l.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Ty=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.dc(a,this.B);return a};
g.h.Nx=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),$Ba(this.g)):this.R("handlerMessage",new iCa(a[0],a[1]))};
g.h.IW=function(){this.l.isActive();var a=this.g,b=0;a.tc&&b++;a.Wd&&b++;0!=b||this.connect(this.B,this.A)};J7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
J7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
J7.prototype.B=function(a){a(Error("request timed out"))};var sCa=(0,g.F)(),M7=null,P7=Array(50),O7=-1,Q7=!1;g.A(R7,g.GF);R7.prototype.ke=function(){return this.g};
R7.prototype.contains=function(a){return!!U6(this.g,a)};
R7.prototype.get=function(a){return a?V6(this.g,a):null};
R7.prototype.info=function(a){N7(this.D,a)};g.A(S7,g.GF);var ADa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=S7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Ba)&&this.sF()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Ba)||(g.XD(this.Ba),this.Ba=window.NaN)};
g.h.V=function(){this.stop();S7.ba.V.call(this)};
g.h.sF=function(){this.Ba=window.NaN;this.g=g.lE(K7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.KW,this),onError:(0,g.z)(this.JW,this),ud:(0,g.z)(this.LW,this)})};
g.h.KW=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.R("pairingComplete",new P6(c))};
g.h.JW=function(a){this.g=null;a.status&&404==a.status?this.l>=ADa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=ADa[this.l],this.Ba=g.VD((0,g.z)(this.sF,this),a),this.l++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.LW=function(){this.g=null;this.R("pairingFailed",Error("Server not responding"))};g.A(U7,R7);g.h=U7.prototype;g.h.start=function(){T7(this)&&this.R("screenChange");!g.NG("yt-remote-lounge-token-expiration")&&wCa(this);g.XD(this.l);this.l=g.VD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){T7(this);tCa(this,a);V7(this,!1);this.R("screenChange");b(a);a.token||wCa(this)};
g.h.remove=function(a,b){var c=T7(this);vCa(this,a)&&(V7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.wq=function(a,b,c,d){var e=T7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,V7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.V=function(){g.XD(this.l);U7.ba.V.call(this)};
g.h.YJ=function(a){T7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}V7(this,!b);b&&N7(this.D,"Missed "+b+" lounge tokens.")};
g.h.XJ=function(a){N7(this.D,"Requesting lounge tokens failed: "+a)};g.A(X7,g.GF);g.h=X7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.NG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?Z7(this):(this.A=(0,g.F)()+3E5,g.MG("yt-remote-fast-check-period",this.A),this.lv())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){W7("Updating availability on schedule.");var a=this.C(),b=g.Kb(this.g,function(b,d){return b&&!!V6(a,d)},this);
Y7(this,b)};
g.h.V=function(){g.XD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);X7.ba.V.call(this)};
g.h.lv=function(){g.XD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=zCa(this);if(g.Nb(a)){var b=K7(this.B,"/pairing/get_screen_availability");this.l=L7(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.LT,this,a),(0,g.z)(this.KT,this))}else Y7(this,{}),Z7(this)};
g.h.LT=function(a,b){this.l=null;var c=g.Qb(zCa(this));if(g.ib(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Y7(this,d);Z7(this)}else this.fc("Changing Screen set during request."),this.lv()};
g.h.KT=function(a){this.fc("Screen availability failed: "+a);this.l=null;Z7(this)};
g.h.fc=function(a){N7("OnlineScreenService",a)};g.A($7,R7);g.h=$7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.R("screenChange"),this.l.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.wq=function(a,b,c,d){this.o.contains(a)?this.o.wq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,N7(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Wa(this.g,(0,g.Kd)(this.A,function(a){return!this.contains(a)},this))};
g.h.tF=function(){return(0,g.Kd)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.uF=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new S7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.$e(f);d(a8(this,a))},this));
f.subscribe("pairingFailed",function(a){g.$e(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.NW=function(a,b,c,d){g.lE(K7(this.C,"/pairing/get_screen"),{method:"POST",Mb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new P6(d.screen||{});if(!e.name||DCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);DCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(a8(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
ud:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.V=function(){g.$e(this.o);g.$e(this.l);$7.ba.V.call(this)};
g.h.nK=function(){ECa(this);this.R("screenChange");this.l.update()};
$7.prototype.dispose=$7.prototype.dispose;g.A(c8,g.GF);g.h=c8.prototype;g.h.Bp=function(a){this.o=a;this.R("sessionScreen",this.o)};
g.h.re=function(a){this.ka()||(a&&d8(this,""+a),this.o=null,this.R("sessionScreen",null))};
g.h.info=function(a){N7(this.K,a)};
g.h.wF=function(){return null};
g.h.vv=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){d8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.V=function(){this.vv("");c8.ba.V.call(this)};g.A(e8,c8);g.h=e8.prototype;g.h.uv=function(a){if(this.g){if(this.g==a)return;d8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);GCa(this)};
g.h.ak=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.re()},this),(0,g.z)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.vv=g.y;g.h.V=function(){this.info("disposeInternal");g.XD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;e8.ba.V.call(this)};
g.h.SU=function(a,b){if(!this.ka())if(b){var c=g.Ww(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":FCa(this,c.screenId);break;default:d8(this,"Unknown youtube message: "+d)}}else d8(this,"Unable to parse message.")}else d8(this,"No data in message.")};
g.h.ez=function(a,b,c,d){CCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(d8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.VD((0,g.z)(this.ez,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.wF=function(){return this.g};
g.h.OW=function(a){this.ka()||a||(d8(this,"Cast session died."),this.re())};g.A(f8,c8);g.h=f8.prototype;g.h.uv=function(a){this.A=a;this.A.addUpdateListener(this.J)};
g.h.ak=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.XD(this.C);this.A?this.A.stop((0,g.z)(this.re,this,null),(0,g.z)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.V=function(){this.g();this.g=g.y;g.XD(this.C);this.A&&this.A.removeUpdateListener(this.J);this.A=null;f8.ba.V.call(this)};
g.h.RW=function(a){this.ka()||a||(d8(this,"DIAL session died."),this.g(),this.g=g.y,this.re())};
g.h.ht=function(a){this.I=T6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,ICa(this));a(b);HCa(this)}else this.D=(0,g.z)(function(){g.XD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,ICa(this));a(b);HCa(this)},this),this.C=g.VD((0,g.z)(function(){this.D()},this),100)};
g.h.BL=function(a,b,c){CCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Bp(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ht(b,c)},this),(0,g.z)(function(a){d8(this,"Failed to get DIAL screen: "+a);
this.ht(b,c)},this))};g.A(g8,c8);g8.prototype.stop=function(){this.re()};
g8.prototype.uv=g.y;g8.prototype.ak=function(){g.XD(this.g);this.g=window.NaN;var a=V6(this.H.ke(),this.l.label);a?this.Bp(a):this.re(Error("No such screen"))};
g8.prototype.V=function(){g.XD(this.g);this.g=window.NaN;g8.ba.V.call(this)};g.A(h8,g.GF);g.h=h8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.aD,this),(0,g.z)(this.uT,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.nR,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ka()||(window.chrome.cast.addReceiverActionListener(this.A),pCa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.vF,this)),this.o=KCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.R("yt-remote-cast2-availability-change",j8(this)),b(!0))},this),(0,g.z)(function(a){this.fc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.JV=function(a,b){i8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)i8("Unsetting old screen status: "+this.g.l.friendlyName),k8(this,null)}if(a&&b){if(!this.g){c=V6(this.l.ke(),a);if(!c){i8("setConnectedScreenStatus: Unknown screen.");return}var d=JCa(this,c);d||(i8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.fc("Failed to set initial custom receivers: "+g.yg(a))},this)));
i8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);k8(this,new g8(this.l,d),!0)}this.g.vv(b)}else i8("setConnectedScreenStatus: no screen.")};
g.h.KV=function(a){this.ka()?this.fc("Setting connection data on disposed cast v2"):this.g?this.g.ak(a):this.fc("Setting connection data without a session")};
g.h.QW=function(){this.ka()?this.fc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),k8(this,null)):i8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.aD,this),(0,g.z)(this.RT,this))};
g.h.V=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.vF,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],mCa);g.$e(this.g);h8.ba.V.call(this)};
g.h.fc=function(a){N7("Controller",a)};
g.h.bD=function(a,b){this.g==a&&(b||k8(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.qT=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),i8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)i8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{i8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.R("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:k8(this,
new g8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:k8(this,new f8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:k8(this,new e8(this.l,a));break;default:this.fc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.fc("Stopping receiver w/o session: "+a.friendlyName)}else this.fc("onReceiverAction_ called without receiver.")};
g.h.nR=function(a){if(this.ka())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.fc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.fc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return i8("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.fc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);k8(this,new f8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.BL,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.ht,b))};
g.h.aD=function(a){if(!this.ka()){i8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)i8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),k8(this,new e8(this.l,b),!0);else{this.fc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=V6(this.l.ke(),c.label);
d&&Q6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(i8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.$e(this.g),this.g=new e8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.bD,this,this.g)),this.g.ak(null));this.g.uv(a)}}};
g.h.PW=function(){return this.g?this.g.wF():null};
g.h.RT=function(a){this.ka()||(this.fc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&k8(this,null))};
g.h.uT=function(a){i8("Receiver availability updated: "+a);if(!this.ka()){var b=j8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;j8(this)!=b&&this.R("yt-remote-cast2-availability-change",j8(this))}};
g.h.vF=function(){this.ka()||(this.o=KCa(this),i8("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.fc("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",j8(this)))};
h8.prototype.setLaunchParams=h8.prototype.KV;h8.prototype.setConnectedScreenStatus=h8.prototype.JV;h8.prototype.stopSession=h8.prototype.QW;h8.prototype.getCastSession=h8.prototype.PW;h8.prototype.requestSession=h8.prototype.requestSession;h8.prototype.init=h8.prototype.init;h8.prototype.dispose=h8.prototype.dispose;var q8=[];g.h=v8.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";w8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Xf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+x8(this):this.H};
g.h.clone=function(){return new v8(B8(this))};g.A(D8,g.GF);g.h=D8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,J8(this,"play")):I8(this,"play"),H8(this,1,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,J8(this,"pause")):I8(this,"pause"),H8(this,2,z8(E8(this))),this.R("remotePlayerChange")):F8(this,this.pause)};
g.h.rF=function(a){if(1==this.g){if(this.l){var b=E8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,J8(this,"seekTo",{newTime:a}))}else I8(this,"seekTo",{newTime:a});H8(this,3,a);this.R("remotePlayerChange")}else F8(this,g.Fa(this.rF,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,J8(this,"stopVideo")):I8(this,"stopVideo");var a=E8(this);a.index=-1;a.videoId="";w8(a);G8(this,a);this.R("remotePlayerChange")}else F8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=E8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){N7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.fc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){N7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.fc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);I8(this,"setVolume",e)}c.muted=b;c.volume=a;G8(this,c)}else F8(this,g.Fa(this.setVolume,a,b))};
g.h.rE=function(a,b){if(1==this.g){var c=E8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.dc(d,c.l));I8(this,"setSubtitlesTrack",d);G8(this,c)}else F8(this,g.Fa(this.rE,a,b))};
g.h.gw=function(a,b){if(1==this.g){I8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Fb.id});var c=E8(this);c.audioTrackId=b.Fb.id;G8(this,c)}else F8(this,g.Fa(this.gw,a,b))};
g.h.qF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"previous")}else F8(this,g.Fa(this.qF,a,b))};
g.h.pF=function(a,b){if(1==this.g){if(a&&b){var c=E8(this);A8(c,a,b);G8(this,c)}I8(this,"next")}else F8(this,g.Fa(this.pF,a,b))};
g.h.uy=function(){1==this.g?I8(this,"dismissAutoplay"):F8(this,this.uy)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.R("proxyStateChange",a,this.g)}D8.ba.dispose.call(this)};
g.h.V=function(){XCa(this);this.A=null;this.B.clear();C8(this,null);D8.ba.V.call(this)};
g.h.hw=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.oC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.lT=function(a,b){this.R(a,b)};
g.h.KQ=function(a){if(!a)this.qm(null),C8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=E8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)N7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,G8(this,b)}};
g.h.qm=function(a){N7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),YCa(this),this.R("remotePlayerChange")};
g.h.JQ=function(a){a?(YCa(this),this.R("remotePlayerChange")):this.qm(null)};
g.h.WQ=function(){var a=UCa();a&&C8(this,a)};
g.h.fc=function(a){N7("CP",a)};g.A(K8,g.GF);g.h=K8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;y8(this.Za,m);this.A="UNSUPPORTED";L8("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",
params:g.yg(l)},a,tBa())}else L8("Connecting without params"),this.g.connect({},a,tBa());$Ca(this)};
g.h.dispose=function(){this.ka()||(this.R("beforeDispose"),M8(this,3));K8.ba.dispose.call(this)};
g.h.V=function(){N8(this);P8(this);O8(this);g.XD(this.H);this.H=window.NaN;g.XD(this.I);this.I=window.NaN;this.o=null;g.qF(this.T);this.T.length=0;this.g.dispose();K8.ba.V.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.PJ=function(){this.C(2)};
g.h.OQ=function(){L8("Channel opened");this.M&&(this.M=!1,O8(this),this.K=g.VD((0,g.z)(function(){L8("Timing out waiting for a screen.");this.C(1)},this),15E3));
xBa(jCa(this.g),this.Z)};
g.h.LQ=function(){L8("Channel closed");(0,window.isNaN)(this.B)?$6(!0):$6();this.dispose()};
g.h.MQ=function(a){$6();(0,window.isNaN)(this.F())?(L8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,L8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),M8(this,2))};
g.h.NQ=function(a){a.params?L8("Received: action="+a.action+", params="+g.yg(a.params)):L8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Ww(a.params.devices);this.l=(0,g.G)(a,function(a){return new O6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
cDa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
cDa(this,!1);break;case "remoteConnected":var b=new O6(g.Ww(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new O6(g.Ww(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":eDa(this,a);break;case "nowPlaying":gDa(this,a);break;case "onStateChange":fDa(this,a);break;case "onAdStateChange":hDa(this,a);break;case "onVolumeChanged":iDa(this,a);break;case "onSubtitlesTrackChanged":dDa(this,a);break;case "nowAutoplaying":jDa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.R("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":kDa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:L8("Unrecognized action: "+a.action)}};
g.h.sV=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&Q8(this,"getNowPlaying")}};
K8.prototype.subscribe=K8.prototype.subscribe;K8.prototype.unsubscribeByKey=K8.prototype.Pd;K8.prototype.ga=function(){var a=3;this.ka()||(a=0,(0,window.isNaN)(this.F())?I7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
K8.prototype.getProxyState=K8.prototype.ga;K8.prototype.C=function(a){L8("Disconnecting with "+a);N8(this);this.R("beforeDisconnect",a);1==a&&$6();kCa(this.g,a);this.dispose()};
K8.prototype.disconnect=K8.prototype.C;K8.prototype.fa=function(){var a=this.Za;this.o&&(a=this.Za.clone(),A8(a,this.o,a.index));return B8(a)};
K8.prototype.getPlayerContextData=K8.prototype.fa;
K8.prototype.na=function(a){var b=new v8(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.XD(this.H),this.H=g.VD((0,g.z)(this.sV,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&z8(this.Za)==z8(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.R(a)},this)};
K8.prototype.setPlayerContextData=K8.prototype.na;K8.prototype.X=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
K8.prototype.getOtherConnectedRemoteId=K8.prototype.X;K8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
K8.prototype.getReconnectTimeout=K8.prototype.F;K8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
K8.prototype.getAutoplayMode=K8.prototype.Y;K8.prototype.da=function(){return this.D||""};
K8.prototype.getAutoplayVideoId=K8.prototype.da;K8.prototype.sa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Zt(a.g);a.start()}};
K8.prototype.reconnect=K8.prototype.sa;K8.prototype.ha=function(a,b){Q8(this,a,b);bDa(this)};
K8.prototype.sendMessage=K8.prototype.ha;g.A(R8,R7);g.h=R8.prototype;g.h.ke=function(a){return this.ed.$_gs(a)};
g.h.contains=function(a){return!!this.ed.$_c(a)};
g.h.get=function(a){return this.ed.$_g(a)};
g.h.start=function(){this.ed.$_st()};
g.h.add=function(a,b,c){this.ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ed.$_r(a,b,c)};
g.h.wq=function(a,b,c,d){this.ed.$_un(a,b,c,d)};
g.h.V=function(){for(var a=0,b=this.l.length;a<b;++a)this.ed.$_ubk(this.l[a]);this.l.length=0;this.ed=null;R8.ba.V.call(this)};
g.h.MW=function(){this.R("screenChange")};
g.h.MS=function(){this.R("onlineScreenChange")};
$7.prototype.$_st=$7.prototype.start;$7.prototype.$_gspc=$7.prototype.NW;$7.prototype.$_gsppc=$7.prototype.uF;$7.prototype.$_c=$7.prototype.contains;$7.prototype.$_g=$7.prototype.get;$7.prototype.$_a=$7.prototype.add;$7.prototype.$_un=$7.prototype.wq;$7.prototype.$_r=$7.prototype.remove;$7.prototype.$_gs=$7.prototype.ke;$7.prototype.$_gos=$7.prototype.tF;$7.prototype.$_s=$7.prototype.subscribe;$7.prototype.$_ubk=$7.prototype.Pd;var S8=null,T8=null,h9=null,X8=[];g.q(i9,g.M);g.h=i9.prototype;
g.h.V=function(){g.M.prototype.V.call(this);this.A.stop();this.B.stop();this.J.stop();this.M();this.g.unsubscribe("proxyStateChange",this.YC,this);this.g.unsubscribe("remotePlayerChange",this.tm,this);this.g.unsubscribe("remoteQueueChange",this.Cp,this);this.g.unsubscribe("autoplayUpNext",this.wC,this);this.g.unsubscribe("previousNextChange",this.VC,this);this.g.unsubscribe("nowAutoplaying",this.NC,this);this.g.unsubscribe("autoplayDismissed",this.vC,this);this.g=this.F=null};
g.h.wB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(l9(this)){if(!E8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":E8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.Ij(c[0],c[1]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.gw(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();n9(this,0==c?void 0:c);break;case "control_seek":n9(this,c[0]);break;case "control_subtitles_set_track":m9(this,c[0]);break;case "control_set_audio_track":c=c[0],l9(this)&&this.g.gw(this.l.getVideoData(1).videoId,c)}};
g.h.IQ=function(a){this.J.KJ(a)};
g.h.oW=function(a){this.wB("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.HE=function(){var a=this.l.xc("captions","track");g.Wb(a)||m9(this,a)};
g.h.LC=function(a){if(l9(this)){this.g.unsubscribe("remotePlayerChange",this.tm,this);var b=Math.round(a.volume);a=!!a.muted;var c=E8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.K.start();this.g.subscribe("remotePlayerChange",this.tm,this)}};
g.h.dS=function(){g.Wb(this.C)||wDa(this,this.C);this.D=!1};
g.h.YC=function(a,b){this.B.stop();2==b&&this.EE()};
g.h.tm=function(){if(l9(this)){this.A.stop();var a=E8(this.g);switch(a.g){case 1081:case 1:k9(this,new g.uP(8));this.DE();break;case 1085:case 3:k9(this,new g.uP(9));break;case 1083:case 0:k9(this,new g.uP(2));this.I.stop();j9(this,this.l.getVideoData().lengthSeconds);break;case 1084:k9(this,new g.uP(4));break;case 2:k9(this,new g.uP(4));j9(this,z8(a));break;case -1:k9(this,new g.uP(64));break;case -1E3:k9(this,new g.uP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=
E8(this.g).l;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,wDa(this,a));a=E8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.K.isActive()||this.dF()}else vDa(this)};
g.h.VC=function(){this.l.R("mdxpreviousnextchange")};
g.h.Cp=function(){l9(this)||vDa(this)};
g.h.XI=function(){this.g.uy()};
g.h.wC=function(a){a&&(a=g.lE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.tU,this)}))&&(this.M=(0,g.z)(a.abort,a))};
g.h.tU=function(a,b){var c=new g.oO({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.R("mdxautoplayupnext",c)};
g.h.NC=function(a){(0,window.isNaN)(a)||this.l.R("mdxnowautoplaying",a)};
g.h.vC=function(){this.l.R("mdxautoplaycanceled")};
g.h.HO=function(a,b){-1==E8(this.g).g?n9(this,a):b&&this.g.rF(a)};
g.h.dF=function(){if(l9(this)){var a=E8(this.g);this.o.Ea(this.T);a.muted?this.l.mute():this.l.fg();this.l.setVolume(a.volume);this.T=this.o.O(this.l,"onVolumeChange",this.LC)}};
g.h.DE=function(){this.A.stop();if(!this.g.ka()){var a=E8(this.g);a.kb()&&k9(this,new g.uP(8));j9(this,z8(a));this.A.start()}};
g.h.EE=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.q(o9,g.W);o9.prototype.B=function(a){yDa(this,a.state)};g.q(p9,g.WZ);p9.prototype.J=function(){var a=this.l.xc("remote","receivers");a&&1<a.length&&!this.l.xc("remote","quickCast")?(this.H=g.kb(a,this.C,this),g.XZ(this,(0,g.G)(a,this.C)),a=this.l.xc("remote","currentReceiver"),this.zf(this.C(a)),this.enable(!0)):this.enable(!1)};
p9.prototype.C=function(a){return a.key};
p9.prototype.yf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
p9.prototype.sd=function(a){g.WZ.prototype.sd.call(this,a);this.l.Kd("remote","currentReceiver",this.H[a]);this.B.Qb()};g.q(q9,g.tV);g.h=q9.prototype;g.h.create=function(){pDa(g.EM(g.Y(this.g)));this.C.push(g.SF("yt-remote-before-disconnect",this.EQ,this));this.C.push(g.SF("yt-remote-connection-change",this.vT,this));this.C.push(g.SF("yt-remote-receiver-availability-change",this.WC,this));this.C.push(g.SF("yt-remote-auto-connect",this.tT,this));this.C.push(g.SF("yt-remote-receiver-resumed",this.sT,this));this.WC()};
g.h.load=function(){this.g.iu();g.tV.prototype.load.call(this);this.B=new i9(this,this.g,this.l);var a=(a=uDa())?a.currentTime:0;var b=g9()?new D8(b9(),void 0):null;0==a&&b&&(a=z8(E8(b)));0!=a&&(this.H=a||0,this.g.R("progresssync",a,void 0));xDa(this,this.D,this.D);g.s0(this.g.app,6)};
g.h.unload=function(){this.g.R("mdxautoplaycanceled");this.A=this.o;g.af(this.B,this.l);this.l=this.B=null;g.tV.prototype.unload.call(this);g.s0(this.g.app,5)};
g.h.V=function(){g.TF(this.C);g.tV.prototype.V.call(this)};
g.h.gm=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.wB.apply(this.B,[a].concat(g.pa(c)))};
g.h.GJ=function(){return this.loaded?this.B.suggestion:null};
g.h.Xf=function(){return this.l?E8(this.l).Xf:!1};
g.h.hasNext=function(){return this.l?E8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.vO=function(){var a=E8(this.l),b=this.g.getVideoData();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+x8(a):a.A,isPeggedToLive:1>=(a.C?a.o+x8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+x8(a):a.o,seekableStart:0<a.B?a.B+x8(a):a.B}};
g.h.wO=function(){this.l&&this.l.pF()};
g.h.xO=function(){this.l&&this.l.qF()};
g.h.EQ=function(a){1==a&&(this.I=this.l?E8(this.l):null)};
g.h.vT=function(){var a=g9()?new D8(b9(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.$e(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.getVideoData().videoId&&this.g.aB(a.videoId,z8(a)));this.g.R("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.WC=function(){this.F=[this.o].concat(rDa());var a=c9()||this.o;r9(this,a);this.g.va("onMdxReceiversChange")};
g.h.tT=function(){var a=c9();r9(this,a)};
g.h.sT=function(){this.A=c9()};
g.h.uO=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?t8():r9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&t8(),!0):!1}};
g.h.yO=function(){I8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Hc=function(){return!1};g.jY.remote=q9;})(_yt_player);
